<?php

namespace Modules\Client\Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Database\Eloquent\Model;
use Modules\Admin\Entities\Centre;
use Modules\Client\Entities\Group;
use Carbon\Carbon;
use DB;

class GroupTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Model::unguard();

        // Group::factory()->count(300)->create();

        // //Dummy group
        // DB::table('groups')->insert([       
        //         'name'=>'test group',
        //         'group_number'=>'G0',
        //         'loan_term'=>'6 months',
        //         'zone_name'=>'test zone',
        //         'zone_code'=>'000',
        //         'bank_account_name'=>'FNB',
        //         'bank_account_number'=>'000',
        //         // 'post_office',
        //         // 'meeting_day',
        //         // 'meeting_time',
        //         // 'centre_id',
        //         // 'creator_id',
        //         'area_code'=>'123',
        //         'area_officer'=>'Mary Jane',
        //         'slug'=>'test-group',
        //         'created_at' => Carbon::now(),
        //         'updated_at' => Carbon::now(),
        //     ]);

        $groups = [
            ['centre_name'=>'JACKILAND', 'area_officer'=>'MOTHEPANA', 'group_name'=>'MPEPULE', 'created_at'=>'2022-06-22'],
            ['centre_name'=>'JACKILAND', 'area_officer'=>'MOTHEPANA', 'group_name'=>'PHUTHANANG', 'created_at'=>'2022-06-22'],
            ['centre_name'=>'MAKGWATHANE', 'area_officer'=>'MOTHEPANA', 'group_name'=>'IPOPENG', 'created_at'=>'2022-06-22'],
            ['centre_name'=>'MAKGWATHANE', 'area_officer'=>'MOTHEPANA', 'group_name'=>'MMABATHO', 'created_at'=>'2022-06-22'],
            ['centre_name'=>'MAKGWATHANE', 'area_officer'=>'MOTHEPANA', 'group_name'=>'SWARANANG', 'created_at'=>'2022-06-22'],
            ['centre_name'=>'MAKGWATHANE', 'area_officer'=>'MOTHEPANA', 'group_name'=>'TSOGANG FOUNDATION', 'created_at'=>'2022-03-22'],
            ['centre_name'=>'MAKGWATHANE', 'area_officer'=>'MOTHEPANA', 'group_name'=>'ITHUTENG', 'created_at'=>'2022-07-22'],
            ['centre_name'=>'RETLABONA', 'area_officer'=>'MOTHEPANA', 'group_name'=>'BAHLAKI', 'created_at'=>'2022-05-22'],
            ['centre_name'=>'RETLABONA', 'area_officer'=>'MOTHEPANA', 'group_name'=>'CHABADIMAKETSE', 'created_at'=>'2022-05-22'],
            ['centre_name'=>'IKAGENG', 'area_officer'=>'MOTHEPANA', 'group_name'=>'ATLEGANG', 'created_at'=>'2022-07-22'],
            ['centre_name'=>'IKAGENG', 'area_officer'=>'MOTHEPANA', 'group_name'=>'THREE SISTERS', 'created_at'=>'2022-05-22'],
            ['centre_name'=>'IKAGENG', 'area_officer'=>'MOTHEPANA', 'group_name'=>'KGATELOPELE', 'created_at'=>'2022-05-22'],
            ['centre_name'=>'IKAGENG', 'area_officer'=>'MOTHEPANA', 'group_name'=>'REIKEMI', 'created_at'=>'2022-06-22'],
            ['centre_name'=>'IKAGENG', 'area_officer'=>'MOTHEPANA', 'group_name'=>'BAIPEREKI', 'created_at'=>'2022-06-22'],
            ['centre_name'=>'MOOPONG', 'area_officer'=>'MOTHEPANA', 'group_name'=>'RATANANG', 'created_at'=>'2022-07-22'],
            ['centre_name'=>'MOOPONG', 'area_officer'=>'MOTHEPANA', 'group_name'=>'THEKGO', 'created_at'=>'2022-07-22'],
            ['centre_name'=>'MOOPONG', 'area_officer'=>'MOTHEPANA', 'group_name'=>'IKUKENG', 'created_at'=>'2022-06-22'],
            ['centre_name'=>'MOOPONG', 'area_officer'=>'MOTHEPANA', 'group_name'=>'AGANANG', 'created_at'=>'2022-06-22'],
            ['centre_name'=>'MOOPONG', 'area_officer'=>'MOTHEPANA', 'group_name'=>'LEAGO', 'created_at'=>'2022-06-22'],
            ['centre_name'=>'MOOPONG', 'area_officer'=>'MOTHEPANA', 'group_name'=>'BOTHANANG', 'created_at'=>'2022-07-22'],
            ['centre_name'=>'MOOPONG', 'area_officer'=>'MOTHEPANA', 'group_name'=>'TIANG-MAATLA', 'created_at'=>'2022-07-22'],
            ['centre_name'=>'TOOSENG', 'area_officer'=>'MOTHEPANA', 'group_name'=>'THABANG', 'created_at'=>'2022-03-22'],
            ['centre_name'=>'TOOSENG', 'area_officer'=>'MOTHEPANA', 'group_name'=>'THAROLLO', 'created_at'=>'2022-07-22'],
            ['centre_name'=>'TOOSENG', 'area_officer'=>'MOTHEPANA', 'group_name'=>'SEETSA', 'created_at'=>'2022-07-22'],
            ['centre_name'=>'TOOSENG', 'area_officer'=>'MOTHEPANA', 'group_name'=>'SADIBANA KOKOTLELA', 'created_at'=>'2022-08-22'],
            ['centre_name'=>'TOOSENG', 'area_officer'=>'MOTHEPANA', 'group_name'=>'RATANANG', 'created_at'=>'2022-08-22'],
            ['centre_name'=>'LENTING', 'area_officer'=>'MOTHEPANA', 'group_name'=>'EKAGENG', 'created_at'=>'2022-04-22'],
            ['centre_name'=>'LENTING', 'area_officer'=>'MOTHEPANA', 'group_name'=>'EKAGENG-2', 'created_at'=>'2022-08-22'],
            ['centre_name'=>'LENTING', 'area_officer'=>'MOTHEPANA', 'group_name'=>'KOPANO', 'created_at'=>'2022-04-22'],
            ['centre_name'=>'LENTING', 'area_officer'=>'MOTHEPANA', 'group_name'=>'KOPANO-2', 'created_at'=>'2022-08-22'],
            ['centre_name'=>'Unit F', 'area_officer'=>'MOTHEPANA', 'group_name'=>'REKGONNE-2', 'created_at'=>'2022-04-22'],
            ['centre_name'=>'Unit F', 'area_officer'=>'MOTHEPANA', 'group_name'=>'REKGONNE', 'created_at'=>'2022-08-22'],
            ['centre_name'=>'Unit F', 'area_officer'=>'MOTHEPANA', 'group_name'=>'SWARANANG', 'created_at'=>'2022-04-22'],
            ['centre_name'=>'Unit F', 'area_officer'=>'MOTHEPANA', 'group_name'=>'SWARANANG-2', 'created_at'=>'2022-08-22'],
            ['centre_name'=>'Unit F', 'area_officer'=>'MOTHEPANA', 'group_name'=>'KHUTSANG', 'created_at'=>'2022-06-22'],
            ['centre_name'=>'Unit F', 'area_officer'=>'MOTHEPANA', 'group_name'=>'KOPANANG', 'created_at'=>'2022-07-22'],
            ['centre_name'=>'UNIT S', 'area_officer'=>'MOTHEPANA', 'group_name'=>'REGONA', 'created_at'=>'2022-05-22'],
            ['centre_name'=>'UNIT S', 'area_officer'=>'MOTHEPANA', 'group_name'=>'TOP 5', 'created_at'=>'2022-05-22'],
            ['centre_name'=>'UNIT S', 'area_officer'=>'MOTHEPANA', 'group_name'=>'COMFORT', 'created_at'=>'2022-05-22'],
            ['centre_name'=>'UNIT S', 'area_officer'=>'MOTHEPANA', 'group_name'=>'LOTANANG', 'created_at'=>'2022-05-22'],
            ['centre_name'=>'UNIT S', 'area_officer'=>'MOTHEPANA', 'group_name'=>'REFENTSE', 'created_at'=>'2022-06-22'],
            ['centre_name'=>'UNIT S', 'area_officer'=>'MOTHEPANA', 'group_name'=>'RE TLA KGONA', 'created_at'=>'2022-06-22'],
            ['centre_name'=>'UNIT S', 'area_officer'=>'MOTHEPANA', 'group_name'=>'ITSOSHENG', 'created_at'=>'2022-06-22'],
            ['centre_name'=>'UNIT S', 'area_officer'=>'MOTHEPANA', 'group_name'=>'THUSHANANG', 'created_at'=>'2022-06-22'],
            ['centre_name'=>'MURULENG', 'area_officer'=>'MOTHEPANA', 'group_name'=>'BOTANANG', 'created_at'=>'2022-06-22'],
            ['centre_name'=>'MURULENG', 'area_officer'=>'MOTHEPANA', 'group_name'=>'KGATELOPELE', 'created_at'=>'2022-06-22'],
            ['centre_name'=>'MURULENG', 'area_officer'=>'MOTHEPANA', 'group_name'=>'TLAMANANANNG', 'created_at'=>'2022-08-22'],
            ['centre_name'=>'EMFUNDWENI', 'area_officer'=>'KGOSI', 'group_name'=>'NTHATHAKUSA', 'created_at'=>'2022-07-22'],
            ['centre_name'=>'EMFUNDWENI', 'area_officer'=>'KGOSI', 'group_name'=>'SIYANQOBA', 'created_at'=>'2022-02-22'],
            ['centre_name'=>'EMFUNDWENI', 'area_officer'=>'KGOSI', 'group_name'=>'CELUMUSA', 'created_at'=>'2022-04-22'],
            ['centre_name'=>'EMFUNDWENI', 'area_officer'=>'KGOSI', 'group_name'=>'UMYENZANA', 'created_at'=>'2022-04-22'],
            ['centre_name'=>'EMFUNDWENI', 'area_officer'=>'KGOSI', 'group_name'=>'UMYENZANA-2', 'created_at'=>'2022-08-22'],
            ['centre_name'=>'EMFUNDWENI', 'area_officer'=>'KGOSI', 'group_name'=>'SIWELILE', 'created_at'=>'2022-05-22'],
            ['centre_name'=>'EMFUNDWENI', 'area_officer'=>'KGOSI', 'group_name'=>'SIYAPHAMBILI', 'created_at'=>'2022-03-22'],
            ['centre_name'=>'EMFUNDWENI', 'area_officer'=>'KGOSI', 'group_name'=>'AYANDA', 'created_at'=>'2022-05-22'],
            ['centre_name'=>'EMFUNDWENI', 'area_officer'=>'KGOSI', 'group_name'=>'ZAMAZAMA', 'created_at'=>'2022-07-22'],
            ['centre_name'=>'EMFUNDWENI', 'area_officer'=>'KGOSI', 'group_name'=>'CELUKHANYA', 'created_at'=>'2022-08-22'],
            ['centre_name'=>'SKOPALLEN 1', 'area_officer'=>'KGOSI', 'group_name'=>'NGANELIHLE', 'created_at'=>'2022-04-22'],
            ['centre_name'=>'SKOPALLEN 1', 'area_officer'=>'KGOSI', 'group_name'=>'NGANELIHLE-2', 'created_at'=>'2022-08-22'],
            ['centre_name'=>'SKOPALLEN 1', 'area_officer'=>'KGOSI', 'group_name'=>'SIYATHUTHUKA', 'created_at'=>'2022-04-22'],
            ['centre_name'=>'SKOPALLEN 2', 'area_officer'=>'KGOSI', 'group_name'=>'ASETHEMBANE', 'created_at'=>'2022-06-22'],
            ['centre_name'=>'SKOPALLEN 2', 'area_officer'=>'KGOSI', 'group_name'=>'SIYANQOBA', 'created_at'=>'2022-04-22'],
            ['centre_name'=>'SKOPALLEN 2', 'area_officer'=>'KGOSI', 'group_name'=>'SENZOKUHLE', 'created_at'=>'2022-03-22'],
            ['centre_name'=>'SKOPALLEN 2', 'area_officer'=>'KGOSI', 'group_name'=>'BOITUMELO', 'created_at'=>'2022-04-22'],
            ['centre_name'=>'SKOPALLEN 2', 'area_officer'=>'KGOSI', 'group_name'=>'GALION', 'created_at'=>'2022-06-22'],
            ['centre_name'=>'VIEDRIET', 'area_officer'=>'KGOSI', 'group_name'=>'BAMBANANI', 'created_at'=>'2022-09-21'],
            ['centre_name'=>'VIEDRIET', 'area_officer'=>'KGOSI', 'group_name'=>'SIZOLWETHU', 'created_at'=>'2022-04-22'],
            ['centre_name'=>'VIEDRIET', 'area_officer'=>'KGOSI', 'group_name'=>'ABAQOBI', 'created_at'=>'2022-04-22'],
            ['centre_name'=>'VIEDRIET', 'area_officer'=>'KGOSI', 'group_name'=>'SIBEKITHEMBA', 'created_at'=>'2022-04-22'],
            ['centre_name'=>'VIEDRIET', 'area_officer'=>'KGOSI', 'group_name'=>'THUTHUKANI', 'created_at'=>'2022-04-22'],
            ['centre_name'=>'VIEDRIET', 'area_officer'=>'KGOSI', 'group_name'=>'PHAKAMANI', 'created_at'=>'2022-04-22'],
            ['centre_name'=>'VIEDRIET', 'area_officer'=>'KGOSI', 'group_name'=>'NSELELO', 'created_at'=>'2022-06-22'],
            ['centre_name'=>'VIEDRIET', 'area_officer'=>'KGOSI', 'group_name'=>'SIPHIWE OKUHLE', 'created_at'=>'2022-06-22'],
            ['centre_name'=>'KILLKEEL1', 'area_officer'=>'KGOSI', 'group_name'=>'FISOKUHLE', 'created_at'=>'2022-06-22'],
            ['centre_name'=>'KILLKEEL1', 'area_officer'=>'KGOSI', 'group_name'=>'IKUSASALETHU/ICEBOLETHU', 'created_at'=>'2022-02-22'],
            ['centre_name'=>'KILLKEEL1', 'area_officer'=>'KGOSI', 'group_name'=>'IKUSASALETHU/ICEBOLETHU-2', 'created_at'=>'2022-08-22'],
            ['centre_name'=>'KILLKEEL1', 'area_officer'=>'KGOSI', 'group_name'=>'PHUMAPHAMBILI', 'created_at'=>'2022-06-22'],
            ['centre_name'=>'KILLKEEL1', 'area_officer'=>'KGOSI', 'group_name'=>'SICELOKUHLE', 'created_at'=>'2022-06-22'],
            ['centre_name'=>'KILLKEEL1', 'area_officer'=>'KGOSI', 'group_name'=>'LINDOKUHLE', 'created_at'=>'2022-08-22'],
            ['centre_name'=>'KILKEEL2', 'area_officer'=>'KGOSI', 'group_name'=>'ABAQOBI', 'created_at'=>'2022-09-21'],
            ['centre_name'=>'KILKEEL2', 'area_officer'=>'KGOSI', 'group_name'=>'SIPHILAKAHLE', 'created_at'=>'2022-09-21'],
            ['centre_name'=>'KILKEEL2', 'area_officer'=>'KGOSI', 'group_name'=>'THANDOLWETHU 2', 'created_at'=>'2022-02-22'],
            ['centre_name'=>'FAIRBREEZE', 'area_officer'=>'KGOSI', 'group_name'=>'SIYANDA', 'created_at'=>'2022-04-22'],
            ['centre_name'=>'FAIRBREEZE', 'area_officer'=>'KGOSI', 'group_name'=>'SIZIMELE', 'created_at'=>'2022-04-22'],
            ['centre_name'=>'FAIRBREEZE', 'area_officer'=>'KGOSI', 'group_name'=>'SIYAZAMA', 'created_at'=>'2022-04-22'],
            ['centre_name'=>'FAIRBREEZE', 'area_officer'=>'KGOSI', 'group_name'=>'IQOPHELO', 'created_at'=>'2022-04-22'],
            ['centre_name'=>'FAIRBREEZE', 'area_officer'=>'KGOSI', 'group_name'=>'SYAZAMA 1', 'created_at'=>'2022-06-22'],
            ['centre_name'=>'HILLTOP', 'area_officer'=>'KGOSI', 'group_name'=>'SLINDOKUHLE', 'created_at'=>'2022-06-22'],
            ['centre_name'=>'HILLTOP', 'area_officer'=>'KGOSI', 'group_name'=>'BUMBANO', 'created_at'=>'2022-06-22'],
            ['centre_name'=>'SPHUMELELE', 'area_officer'=>'MAPULA', 'group_name'=>'SIYANQOBA', 'created_at'=>'2022-05-22'],
            ['centre_name'=>'SPHUMELELE', 'area_officer'=>'MAPULA', 'group_name'=>'SIYANQOBA 2', 'created_at'=>'2022-06-22'],
            ['centre_name'=>'SPHUMELELE', 'area_officer'=>'MAPULA', 'group_name'=>'HLUMANI', 'created_at'=>'2022-05-22'],
            ['centre_name'=>'SPHUMELELE', 'area_officer'=>'MAPULA', 'group_name'=>'OFENTSE', 'created_at'=>'2022-05-22'],
            ['centre_name'=>'SPHUMELELE', 'area_officer'=>'MAPULA', 'group_name'=>'SUKUMANE', 'created_at'=>'2022-06-22'],
            ['centre_name'=>'SPHUMELELE', 'area_officer'=>'MAPULA', 'group_name'=>'SIZOLWETHU', 'created_at'=>'2022-06-22'],
            ['centre_name'=>'SPHUMELELE', 'area_officer'=>'MAPULA', 'group_name'=>'SIBAMBENI', 'created_at'=>'2022-07-22'],
            ['centre_name'=>'SPHUMELELE', 'area_officer'=>'MAPULA', 'group_name'=>'MASAKHANE', 'created_at'=>'2022-07-22'],
            ['centre_name'=>'KUTLWANO', 'area_officer'=>'MAPULA', 'group_name'=>'VUKUZENZELE', 'created_at'=>'2022-05-22'],
            ['centre_name'=>'KUTLWANO', 'area_officer'=>'MAPULA', 'group_name'=>'ITIRELENG', 'created_at'=>'2022-05-22'],
            ['centre_name'=>'KUTLWANO', 'area_officer'=>'MAPULA', 'group_name'=>'MASAKANE', 'created_at'=>'2022-05-22'],
            ['centre_name'=>'KUTLWANO', 'area_officer'=>'MAPULA', 'group_name'=>'SINQOBILE', 'created_at'=>'2022-05-22'],
            ['centre_name'=>'KUTLWANO', 'area_officer'=>'MAPULA', 'group_name'=>'MASIBAMBANE', 'created_at'=>'2022-05-22'],
            ['centre_name'=>'KUTLWANO', 'area_officer'=>'MAPULA', 'group_name'=>'TSHWARANANG', 'created_at'=>'2022-05-22'],
            ['centre_name'=>'KUTLWANO', 'area_officer'=>'MAPULA', 'group_name'=>'THUBELIHLE', 'created_at'=>'2022-05-22'],
            ['centre_name'=>'KUTLWANO', 'area_officer'=>'MAPULA', 'group_name'=>'SIYAQOBA', 'created_at'=>'2022-05-22'],
            ['centre_name'=>'KUTLWANO', 'area_officer'=>'MAPULA', 'group_name'=>'ASIBAMBANE', 'created_at'=>'2022-05-22'],
            ['centre_name'=>'KUTLWANO', 'area_officer'=>'MAPULA', 'group_name'=>'MPUMELELO', 'created_at'=>'2022-05-22'],
            ['centre_name'=>'KUTLWANO', 'area_officer'=>'MAPULA', 'group_name'=>'KOPANO', 'created_at'=>'2022-06-22'],
            ['centre_name'=>'KUTLWANO', 'area_officer'=>'MAPULA', 'group_name'=>'SEBENZA MAMA', 'created_at'=>'2022-06-22'],
            ['centre_name'=>'KUTLWANO', 'area_officer'=>'MAPULA', 'group_name'=>'THANDANANI', 'created_at'=>'2022-06-22'],
            ['centre_name'=>'KUTLWANO', 'area_officer'=>'MAPULA', 'group_name'=>'ARISE', 'created_at'=>'2022-07-22'],
            ['centre_name'=>'KUTLWANO', 'area_officer'=>'MAPULA', 'group_name'=>'MBALIS', 'created_at'=>'2022-07-22'],
            ['centre_name'=>'KUTLWANO', 'area_officer'=>'MAPULA', 'group_name'=>'PHAKAMANIBAVAZI', 'created_at'=>'2022-07-22'],
            ['centre_name'=>'KUTLWANO', 'area_officer'=>'MAPULA', 'group_name'=>'NKOSINATI', 'created_at'=>'2022-07-22'],
            ['centre_name'=>'KUTLWANO', 'area_officer'=>'MAPULA', 'group_name'=>'SMARTWOMEN', 'created_at'=>'2022-07-22'],
            ['centre_name'=>'KUTLWANO', 'area_officer'=>'MAPULA', 'group_name'=>'SIYAMUKELE', 'created_at'=>'2022-07-22'],
            ['centre_name'=>'TOLSKRAAL', 'area_officer'=>'MAPULA', 'group_name'=>'VULINDLELA', 'created_at'=>'2022-06-22'],
            ['centre_name'=>'TOLSKRAAL', 'area_officer'=>'MAPULA', 'group_name'=>'MPUMELELO', 'created_at'=>'2022-06-22'],
            ['centre_name'=>'TOLSKRAAL', 'area_officer'=>'MAPULA', 'group_name'=>'SEDIBA', 'created_at'=>'2022-06-22'],
            ['centre_name'=>'TOLSKRAAL', 'area_officer'=>'MAPULA', 'group_name'=>'SEKIMA', 'created_at'=>'2022-06-22'],
            ['centre_name'=>'TOLSKRAAL', 'area_officer'=>'MAPULA', 'group_name'=>'SIVELAPHI', 'created_at'=>'2022-06-22'],
            ['centre_name'=>'ARETSOGENG', 'area_officer'=>'MAPULA', 'group_name'=>'ARETSOGENG', 'created_at'=>'2022-07-22'],
            ['centre_name'=>'ARETSOGENG', 'area_officer'=>'MAPULA', 'group_name'=>'SEHLANGASANONYANE', 'created_at'=>'2022-07-22'],
            ['centre_name'=>'ARETSOGENG', 'area_officer'=>'MAPULA', 'group_name'=>'FANTASTIC THREE', 'created_at'=>'2022-07-22'],
            ['centre_name'=>'BOTHA', 'area_officer'=>'PRISCA', 'group_name'=>'BAIPEI', 'created_at'=>'2022-07-22'],
            ['centre_name'=>'BOTHA', 'area_officer'=>'PRISCA', 'group_name'=>'HLOMPHO', 'created_at'=>'2022-07-22'],
            ['centre_name'=>'BOTHA', 'area_officer'=>'PRISCA', 'group_name'=>'LETAMAAKO', 'created_at'=>'2022-07-22'],
            ['centre_name'=>'BOTHA', 'area_officer'=>'PRISCA', 'group_name'=>'PHOMOLO', 'created_at'=>'2022-07-22'],
            ['centre_name'=>'BOTHA', 'area_officer'=>'PRISCA', 'group_name'=>'RETHABILE', 'created_at'=>'2022-04-22'],
            ['centre_name'=>'BOTHA', 'area_officer'=>'PRISCA', 'group_name'=>'RETHABILE-2', 'created_at'=>'2022-08-22'],
            ['centre_name'=>'BOTHA', 'area_officer'=>'PRISCA', 'group_name'=>'REAMOGETSWE', 'created_at'=>'2022-07-22'],
            ['centre_name'=>'BOTHA', 'area_officer'=>'PRISCA', 'group_name'=>'BADIRAMMOGO', 'created_at'=>'2022-05-22'],
            ['centre_name'=>'BOTHA', 'area_officer'=>'PRISCA', 'group_name'=>'SIYABONGA', 'created_at'=>'2022-05-22'],
            ['centre_name'=>'BOTHA', 'area_officer'=>'PRISCA', 'group_name'=>'THABANG', 'created_at'=>'2022-05-22'],
            ['centre_name'=>'BOTHA', 'area_officer'=>'PRISCA', 'group_name'=>'TSHWARANANG', 'created_at'=>'2022-05-22'],
            ['centre_name'=>'DRIEFONTEIN', 'area_officer'=>'PRISCA', 'group_name'=>'LETLHABILE', 'created_at'=>'2022-07-22'],
            ['centre_name'=>'DRIEFONTEIN', 'area_officer'=>'PRISCA', 'group_name'=>'RETHABILE', 'created_at'=>'2022-07-22'],
            ['centre_name'=>'DRIEFONTEIN', 'area_officer'=>'PRISCA', 'group_name'=>'THAKGALANG', 'created_at'=>'2022-07-22'],
            ['centre_name'=>'DRIEFONTEIN', 'area_officer'=>'PRISCA', 'group_name'=>'TSHWARANANG', 'created_at'=>'2022-07-22'],
            ['centre_name'=>'DRIEFONTEIN', 'area_officer'=>'PRISCA', 'group_name'=>'RETHABELENG', 'created_at'=>'2022-05-22'],
            ['centre_name'=>'DRIEFONTEIN', 'area_officer'=>'PRISCA', 'group_name'=>'REPHAFOGILE', 'created_at'=>'2022-06-22'],
            ['centre_name'=>'DRIEFONTEIN', 'area_officer'=>'PRISCA', 'group_name'=>'IPOPENG', 'created_at'=>'2022-06-22'],
            ['centre_name'=>'MATLEREKENG', 'area_officer'=>'PRISCA', 'group_name'=>'HLOMPHANANG', 'created_at'=>'2022-05-22'],
            ['centre_name'=>'MATLEREKENG', 'area_officer'=>'PRISCA', 'group_name'=>'SWARANANG', 'created_at'=>'2022-05-22'],
            ['centre_name'=>'MATLEREKENG', 'area_officer'=>'PRISCA', 'group_name'=>'IKEMELENG', 'created_at'=>'2022-05-22'],
            ['centre_name'=>'MATLEREKENG', 'area_officer'=>'PRISCA', 'group_name'=>'TSWELOPELE', 'created_at'=>'2022-05-22'],
            ['centre_name'=>'MATLEREKENG', 'area_officer'=>'PRISCA', 'group_name'=>'ARETSEBANENG BASADI', 'created_at'=>'2022-06-22'],
            ['centre_name'=>'MATLEREKENG', 'area_officer'=>'PRISCA', 'group_name'=>'IPOPENG', 'created_at'=>'2022-07-22'],
            ['centre_name'=>'TSHIKANOSI', 'area_officer'=>'PRISCA', 'group_name'=>'KGOTLELELO', 'created_at'=>'2022-04-22'],
            ['centre_name'=>'TSHIKANOSI', 'area_officer'=>'PRISCA', 'group_name'=>'KGOTLELELO-2', 'created_at'=>'2022-08-22'],
            ['centre_name'=>'TSHIKANOSI', 'area_officer'=>'PRISCA', 'group_name'=>'REATLEGILE', 'created_at'=>'2022-04-22'],
            ['centre_name'=>'TSHIKANOSI', 'area_officer'=>'PRISCA', 'group_name'=>'REATLEGILE-2', 'created_at'=>'2022-08-22'],
            ['centre_name'=>'TSHIKANOSI', 'area_officer'=>'PRISCA', 'group_name'=>'IKETLENG', 'created_at'=>'2022-04-22'],
            ['centre_name'=>'TSHIKANOSI', 'area_officer'=>'PRISCA', 'group_name'=>'IKETLENG-2', 'created_at'=>'2022-08-22'],
            ['centre_name'=>'TSHIKANOSI', 'area_officer'=>'PRISCA', 'group_name'=>'ITUMELENG', 'created_at'=>'2022-04-22'],
            ['centre_name'=>'TSHIKANOSI', 'area_officer'=>'PRISCA', 'group_name'=>'ITUMELENG-2', 'created_at'=>'2022-08-22'],
            ['centre_name'=>'TSHIKANOSI', 'area_officer'=>'PRISCA', 'group_name'=>'THUSANO', 'created_at'=>'2022-05-22'],
            ['centre_name'=>'TSHIKANOSI', 'area_officer'=>'PRISCA', 'group_name'=>'NKGODISHENG', 'created_at'=>'2022-07-22'],
            ['centre_name'=>'RATHOKE', 'area_officer'=>'PRISCA', 'group_name'=>'RETHABILE', 'created_at'=>'2022-07-22'],
            ['centre_name'=>'RATHOKE', 'area_officer'=>'PRISCA', 'group_name'=>'THEKGANANG', 'created_at'=>'2022-07-22'],
            ['centre_name'=>'RATHOKE', 'area_officer'=>'PRISCA', 'group_name'=>'TSHEPANG', 'created_at'=>'2022-07-22'],
            ['centre_name'=>'RATHOKE', 'area_officer'=>'PRISCA', 'group_name'=>'MONTSHEPETSA', 'created_at'=>'2022-04-22'],
            ['centre_name'=>'RATHOKE', 'area_officer'=>'PRISCA', 'group_name'=>'MONTSHEPETSA-2', 'created_at'=>'2022-08-22'],
            ['centre_name'=>'RATHOKE', 'area_officer'=>'PRISCA', 'group_name'=>'THAKGALANG CLUB', 'created_at'=>'2022-05-22'],
            ['centre_name'=>'RATHOKE', 'area_officer'=>'PRISCA', 'group_name'=>'LETHABO SUNRISE', 'created_at'=>'2022-05-22'],
            ['centre_name'=>'RATHOKE', 'area_officer'=>'PRISCA', 'group_name'=>'POTLAKO', 'created_at'=>'2022-05-22'],
            ['centre_name'=>'RATHOKE', 'area_officer'=>'PRISCA', 'group_name'=>'POELANO', 'created_at'=>'2022-05-22'],
            ['centre_name'=>'RATHOKE', 'area_officer'=>'PRISCA', 'group_name'=>'BLESSING', 'created_at'=>'2022-05-22'],
            ['centre_name'=>'RATHOKE', 'area_officer'=>'PRISCA', 'group_name'=>'SIMUNYE', 'created_at'=>'2022-06-22'],
            ['centre_name'=>'RATHOKE', 'area_officer'=>'PRISCA', 'group_name'=>'TSOSHANANG', 'created_at'=>'2022-08-22'],
            ['centre_name'=>'LEFISO', 'area_officer'=>'PRISCA', 'group_name'=>'SISONKE LADIES', 'created_at'=>'2022-06-22'],
            ['centre_name'=>'LEFISO', 'area_officer'=>'PRISCA', 'group_name'=>'IPOPENG', 'created_at'=>'2022-06-22'],
            ['centre_name'=>'LEFISO', 'area_officer'=>'PRISCA', 'group_name'=>'BOIKANYO', 'created_at'=>'2022-06-22'],
            ['centre_name'=>'LEFISO', 'area_officer'=>'PRISCA', 'group_name'=>'REATLEGILE', 'created_at'=>'2022-06-22'],
            ['centre_name'=>'SENOTLELO', 'area_officer'=>'PRISCA', 'group_name'=>'IKAGENG', 'created_at'=>'2022-07-22'],
            ['centre_name'=>'SENOTLELO', 'area_officer'=>'PRISCA', 'group_name'=>'REIKEMETSE', 'created_at'=>'2022-07-22'],
            ['centre_name'=>'SENOTLELO', 'area_officer'=>'PRISCA', 'group_name'=>'THUSANANG', 'created_at'=>'2022-07-22'],
            ['centre_name'=>'SENOTLELO', 'area_officer'=>'PRISCA', 'group_name'=>'KGATELEPELE', 'created_at'=>'2022-07-22'],
            ['centre_name'=>'VAALBANK', 'area_officer'=>'MINAH', 'group_name'=>'REAKGONA', 'created_at'=>'2022-05-22'],
            ['centre_name'=>'VAALBANK', 'area_officer'=>'MINAH', 'group_name'=>'KHOMANANI', 'created_at'=>'2022-04-22'],
            ['centre_name'=>'VAALBANK', 'area_officer'=>'MINAH', 'group_name'=>'KHOMANANI-2', 'created_at'=>'2022-08-22'],
            ['centre_name'=>'VAALBANK', 'area_officer'=>'MINAH', 'group_name'=>'ITSOSENG 1', 'created_at'=>'2022-04-22'],
            ['centre_name'=>'VAALBANK', 'area_officer'=>'MINAH', 'group_name'=>'ITSOSENG 1-2', 'created_at'=>'2022-08-22'],
            ['centre_name'=>'VAALBANK', 'area_officer'=>'MINAH', 'group_name'=>'ITSOSENG 2', 'created_at'=>'2022-04-22'],
            ['centre_name'=>'VAALBANK', 'area_officer'=>'MINAH', 'group_name'=>'ITSOSENG 2-2', 'created_at'=>'2022-08-22'],
            ['centre_name'=>'VAALBANK', 'area_officer'=>'MINAH', 'group_name'=>'KAGISANO', 'created_at'=>'2022-05-22'],
            ['centre_name'=>'VAALBANK', 'area_officer'=>'MINAH', 'group_name'=>'TSHWARANANG', 'created_at'=>'2022-05-22'],
            ['centre_name'=>'VAALBANK', 'area_officer'=>'MINAH', 'group_name'=>'RETHABILE', 'created_at'=>'2022-05-22'],
            ['centre_name'=>'VAALBANK', 'area_officer'=>'MINAH', 'group_name'=>'REAETEKA', 'created_at'=>'2022-05-22'],
            ['centre_name'=>'VAALBANK', 'area_officer'=>'MINAH', 'group_name'=>'FAMILY FRIEND', 'created_at'=>'2022-06-22'],
            ['centre_name'=>'ITSOSENG', 'area_officer'=>'MINAH', 'group_name'=>'RETHABILE', 'created_at'=>'2022-05-22'],
            ['centre_name'=>'ITSOSENG', 'area_officer'=>'MINAH', 'group_name'=>'BADIRAMMOGO', 'created_at'=>'2022-05-22'],
            ['centre_name'=>'ITSOSENG', 'area_officer'=>'MINAH', 'group_name'=>'ATLEGANG', 'created_at'=>'2022-05-22'],
            ['centre_name'=>'ITSOSENG', 'area_officer'=>'MINAH', 'group_name'=>'TSHEPANG', 'created_at'=>'2022-05-22'],
            ['centre_name'=>'ITSOSENG', 'area_officer'=>'MINAH', 'group_name'=>'TSHIMOLOGO', 'created_at'=>'2022-05-22'],
            ['centre_name'=>'ITSOSENG', 'area_officer'=>'MINAH', 'group_name'=>'HARERATANENG', 'created_at'=>'2022-06-22'],
            ['centre_name'=>'ITSOSENG', 'area_officer'=>'MINAH', 'group_name'=>'IPOPENG', 'created_at'=>'2022-07-22'],
            ['centre_name'=>'AGANANG', 'area_officer'=>'MINAH', 'group_name'=>'IKAGENG', 'created_at'=>'2022-06-22'],
            ['centre_name'=>'AGANANG', 'area_officer'=>'MINAH', 'group_name'=>'RETHABILE', 'created_at'=>'2022-06-22'],
            ['centre_name'=>'AGANANG', 'area_officer'=>'MINAH', 'group_name'=>'KAGISO', 'created_at'=>'2022-06-22'],
            ['centre_name'=>'AGANANG', 'area_officer'=>'MINAH', 'group_name'=>'BOKAMOSO', 'created_at'=>'2022-06-22'],
            ['centre_name'=>'AGANANG', 'area_officer'=>'MINAH', 'group_name'=>'TSOGANG', 'created_at'=>'2022-06-22'],
            ['centre_name'=>'AGANANG', 'area_officer'=>'MINAH', 'group_name'=>'LETHABO', 'created_at'=>'2022-06-22'],
            ['centre_name'=>'AGANANG', 'area_officer'=>'MINAH', 'group_name'=>'KOPANO', 'created_at'=>'2022-06-22'],
            ['centre_name'=>'MAKGAREBE', 'area_officer'=>'MINAH', 'group_name'=>'SKEEM SAAM', 'created_at'=>'2022-07-22'],
            ['centre_name'=>'MAKGAREBE', 'area_officer'=>'MINAH', 'group_name'=>'ATLEGANG', 'created_at'=>'2022-07-22'],
            ['centre_name'=>'MAKGAREBE', 'area_officer'=>'MINAH', 'group_name'=>'REAETEKA 2', 'created_at'=>'2022-05-22'],
            ['centre_name'=>'TSOSANANG', 'area_officer'=>'MINAH', 'group_name'=>'TUMISANG', 'created_at'=>'2022-07-22'],
            ['centre_name'=>'TSOSANANG', 'area_officer'=>'MINAH', 'group_name'=>'BLESSING', 'created_at'=>'2022-07-22'],
            ['centre_name'=>'TSOSANANG', 'area_officer'=>'MINAH', 'group_name'=>'KAGISANO', 'created_at'=>'2022-07-22'],
            ['centre_name'=>'DIHLAKANENG', 'area_officer'=>'KGADI', 'group_name'=>'IPOPENG', 'created_at'=>'2022-05-22'],
            ['centre_name'=>'DIHLAKANENG', 'area_officer'=>'KGADI', 'group_name'=>'MATSOGOAJELWA', 'created_at'=>'2022-05-22'],
            ['centre_name'=>'DIHLAKANENG', 'area_officer'=>'KGADI', 'group_name'=>'IKAGENG', 'created_at'=>'2022-05-22'],
            ['centre_name'=>'DIHLAKANENG', 'area_officer'=>'KGADI', 'group_name'=>'THUSHANANG', 'created_at'=>'2022-05-22'],
            ['centre_name'=>'DIHLAKANENG', 'area_officer'=>'KGADI', 'group_name'=>'ETSOSHENG', 'created_at'=>'2022-05-22'],
            ['centre_name'=>'DIHLAKANENG', 'area_officer'=>'KGADI', 'group_name'=>'BANABAKGWALE', 'created_at'=>'2022-05-22'],
            ['centre_name'=>'MATSHELAMPATA', 'area_officer'=>'KGADI', 'group_name'=>'IKAGENG', 'created_at'=>'2022-05-22'],
            ['centre_name'=>'MATSHELAMPATA', 'area_officer'=>'KGADI', 'group_name'=>'TOKOLOGO', 'created_at'=>'2022-05-22'],
            ['centre_name'=>'MATSHELAMPATA', 'area_officer'=>'KGADI', 'group_name'=>'SEDIBENG', 'created_at'=>'2022-05-22'],
            ['centre_name'=>'MATSHELAMPATA', 'area_officer'=>'KGADI', 'group_name'=>'TUBATSE', 'created_at'=>'2022-05-22'],
            ['centre_name'=>'MATSHELAMPATA', 'area_officer'=>'KGADI', 'group_name'=>'RETHABILE', 'created_at'=>'2022-05-22'],
            ['centre_name'=>'MATSHELAMPATA', 'area_officer'=>'KGADI', 'group_name'=>'AGANANG', 'created_at'=>'2022-05-22'],
            ['centre_name'=>'MATSHELAMPATA', 'area_officer'=>'KGADI', 'group_name'=>'MATSOSE', 'created_at'=>'2022-06-22'],
            ['centre_name'=>'MATSHELAMPATA', 'area_officer'=>'KGADI', 'group_name'=>'MAFOLOFOLO', 'created_at'=>'2022-06-22'],
            ['centre_name'=>'MATSHELAMPATA', 'area_officer'=>'KGADI', 'group_name'=>'OFENTSE', 'created_at'=>'2022-06-22'],
            ['centre_name'=>'SHUSHUMELA', 'area_officer'=>'KGADI', 'group_name'=>'TSHEPISO', 'created_at'=>'2022-05-22'],
            ['centre_name'=>'SHUSHUMELA', 'area_officer'=>'KGADI', 'group_name'=>'LERATO', 'created_at'=>'2022-05-22'],
            ['centre_name'=>'SHUSHUMELA', 'area_officer'=>'KGADI', 'group_name'=>'KOPANANG', 'created_at'=>'2022-05-22'],
            ['centre_name'=>'SHUSHUMELA', 'area_officer'=>'KGADI', 'group_name'=>'RATANANG', 'created_at'=>'2022-05-22'],
            ['centre_name'=>'SHUSHUMELA', 'area_officer'=>'KGADI', 'group_name'=>'ITSOSHENG', 'created_at'=>'2022-05-22'],
            ['centre_name'=>'SHUSHUMELA', 'area_officer'=>'KGADI', 'group_name'=>'REAPHELA', 'created_at'=>'2022-05-22'],
            ['centre_name'=>'GA-RANTO', 'area_officer'=>'KGADI', 'group_name'=>'ITUMELENG', 'created_at'=>'2022-05-22'],
            ['centre_name'=>'GA-RANTO', 'area_officer'=>'KGADI', 'group_name'=>'ITHEKGENG', 'created_at'=>'2022-05-22'],
            ['centre_name'=>'GA-RANTO', 'area_officer'=>'KGADI', 'group_name'=>'THUSHANANG', 'created_at'=>'2022-05-22'],
            ['centre_name'=>'GA-RANTO', 'area_officer'=>'KGADI', 'group_name'=>'MOLAPONG', 'created_at'=>'2022-05-22'],
            ['centre_name'=>'GA-RANTO', 'area_officer'=>'KGADI', 'group_name'=>'KUKANANG', 'created_at'=>'2022-05-22'],
            ['centre_name'=>'GA-RANTO', 'area_officer'=>'KGADI', 'group_name'=>'KGAHLANONG', 'created_at'=>'2022-06-22'],
            ['centre_name'=>'GA-RANTO', 'area_officer'=>'KGADI', 'group_name'=>'ARERATANENG', 'created_at'=>'2022-06-22'],
            ['centre_name'=>'GA-RANTO', 'area_officer'=>'KGADI', 'group_name'=>'NTSWANENG', 'created_at'=>'2022-06-22'],
            ['centre_name'=>'GA-RANTO', 'area_officer'=>'KGADI', 'group_name'=>'TIRISANO', 'created_at'=>'2022-06-22'],
            ['centre_name'=>'GA-RANTO', 'area_officer'=>'KGADI', 'group_name'=>'SPRINGS', 'created_at'=>'2022-06-22'],
            ['centre_name'=>'GA-RANTO', 'area_officer'=>'KGADI', 'group_name'=>'THABANG', 'created_at'=>'2022-06-22'],
            ['centre_name'=>'GA-RANTO', 'area_officer'=>'KGADI', 'group_name'=>'MATSOSHE', 'created_at'=>'2022-06-22'],
            ['centre_name'=>'GA-RANTO', 'area_officer'=>'KGADI', 'group_name'=>'TWANA', 'created_at'=>'2022-07-22'],
            ['centre_name'=>'GA-RANTO', 'area_officer'=>'KGADI', 'group_name'=>'AMOGELANG', 'created_at'=>'2022-07-22'],
            ['centre_name'=>'GA-RANTO', 'area_officer'=>'KGADI', 'group_name'=>'LEGAUDING', 'created_at'=>'2022-06-22'],
            ['centre_name'=>'GA-RANTO', 'area_officer'=>'KGADI', 'group_name'=>'SHAKOANENG', 'created_at'=>'2022-06-22'],
            ['centre_name'=>'GA-RANTO', 'area_officer'=>'KGADI', 'group_name'=>'LESEDI', 'created_at'=>'2022-06-22'],
            ['centre_name'=>'GA-RANTO', 'area_officer'=>'KGADI', 'group_name'=>'LETHABO', 'created_at'=>'2022-06-22'],
            ['centre_name'=>'GA-RANTO', 'area_officer'=>'KGADI', 'group_name'=>'KGOBOKANANG', 'created_at'=>'2022-07-22'],
            ['centre_name'=>'GA-RANTO', 'area_officer'=>'KGADI', 'group_name'=>'ITSOSENG', 'created_at'=>'2022-07-22'],
            ['centre_name'=>'GA-RANTO', 'area_officer'=>'KGADI', 'group_name'=>'LEBATING', 'created_at'=>'2022-06-22'],
            ['centre_name'=>'GA-RANTO', 'area_officer'=>'KGADI', 'group_name'=>'KOPANO', 'created_at'=>'2022-08-22'],
            ['centre_name'=>'GA-RANTO', 'area_officer'=>'KGADI', 'group_name'=>'AREKOPANENG', 'created_at'=>'2022-08-22'],
            ['centre_name'=>'GA-RANTO', 'area_officer'=>'KGADI', 'group_name'=>'ATLEGANG', 'created_at'=>'2022-08-22'],
            ['centre_name'=>'BOFALA', 'area_officer'=>'LEBOGANG', 'group_name'=>'BANANA GROUP', 'created_at'=>'2022-04-22'],
            ['centre_name'=>'BOFALA', 'area_officer'=>'LEBOGANG', 'group_name'=>'BANANA GROUP-2', 'created_at'=>'2022-08-22'],
            ['centre_name'=>'BOFALA', 'area_officer'=>'LEBOGANG', 'group_name'=>'TLEMAGANO', 'created_at'=>'2022-04-22'],
            ['centre_name'=>'BOFALA', 'area_officer'=>'LEBOGANG', 'group_name'=>'TLEMAGANO-2', 'created_at'=>'2022-08-22'],
            ['centre_name'=>'BOFALA', 'area_officer'=>'LEBOGANG', 'group_name'=>'IKAGENG', 'created_at'=>'2022-04-22'],
            ['centre_name'=>'BOFALA', 'area_officer'=>'LEBOGANG', 'group_name'=>'IKAGENG-2', 'created_at'=>'2022-08-22'],
            ['centre_name'=>'BOFALA', 'area_officer'=>'LEBOGANG', 'group_name'=>'BADIRA MMOGO', 'created_at'=>'2022-04-22'],
            ['centre_name'=>'BOFALA', 'area_officer'=>'LEBOGANG', 'group_name'=>'BADIRA MMOGO-2', 'created_at'=>'2022-08-22'],
            ['centre_name'=>'BOFALA', 'area_officer'=>'LEBOGANG', 'group_name'=>'BAKGETHWA', 'created_at'=>'2022-04-22'],
            ['centre_name'=>'BOFALA', 'area_officer'=>'LEBOGANG', 'group_name'=>'BAKGETHWA-2', 'created_at'=>'2022-08-22'],
            ['centre_name'=>'BOFALA', 'area_officer'=>'LEBOGANG', 'group_name'=>'KUTLWANO', 'created_at'=>'2022-07-22'],
            ['centre_name'=>'BOFALA', 'area_officer'=>'LEBOGANG', 'group_name'=>'KOPANO', 'created_at'=>'2022-05-22'],
            ['centre_name'=>'BOFALA', 'area_officer'=>'LEBOGANG', 'group_name'=>'BAUBA', 'created_at'=>'2022-05-22'],
            ['centre_name'=>'BOFALA', 'area_officer'=>'LEBOGANG', 'group_name'=>'MAATLA KE KWANO', 'created_at'=>'2022-05-22'],
            ['centre_name'=>'BOFALA', 'area_officer'=>'LEBOGANG', 'group_name'=>'SENAKADIRA', 'created_at'=>'2022-05-22'],
            ['centre_name'=>'BOFALA', 'area_officer'=>'LEBOGANG', 'group_name'=>'TIRISHANO', 'created_at'=>'2022-06-22'],
            ['centre_name'=>'BOFALA', 'area_officer'=>'LEBOGANG', 'group_name'=>'LERAJANE', 'created_at'=>'2022-05-22'],
            ['centre_name'=>'BOFALA', 'area_officer'=>'LEBOGANG', 'group_name'=>'KWANO', 'created_at'=>'2022-08-22'],
            ['centre_name'=>'MOKOKOTLONG', 'area_officer'=>'LEBOGANG', 'group_name'=>'MALEBO GROUP', 'created_at'=>'2022-07-22'],
            ['centre_name'=>'MOKOKOTLONG', 'area_officer'=>'LEBOGANG', 'group_name'=>'THEKGANANG', 'created_at'=>'2022-03-22'],
            ['centre_name'=>'MOKOKOTLONG', 'area_officer'=>'LEBOGANG', 'group_name'=>'MATLWATLWENG', 'created_at'=>'2022-05-22'],
            ['centre_name'=>'MOKOKOTLONG', 'area_officer'=>'LEBOGANG', 'group_name'=>'DITLOGILE', 'created_at'=>'2022-06-22'],
            ['centre_name'=>'MOKOKOTLONG', 'area_officer'=>'LEBOGANG', 'group_name'=>'NALEDI GROUP', 'created_at'=>'2022-06-22'],
            ['centre_name'=>'MOKOKOTLONG', 'area_officer'=>'LEBOGANG', 'group_name'=>'LEAGO', 'created_at'=>'2022-06-22'],
            ['centre_name'=>'MOKOKOTLONG', 'area_officer'=>'LEBOGANG', 'group_name'=>'MMUPUDU', 'created_at'=>'2022-07-22'],
            ['centre_name'=>'MOKOKOTLONG', 'area_officer'=>'LEBOGANG', 'group_name'=>'BAMBANANI', 'created_at'=>'2022-08-22'],
            ['centre_name'=>'MADITHAME', 'area_officer'=>'LEBOGANG', 'group_name'=>'ETSHEPENG', 'created_at'=>'2022-05-22'],
            ['centre_name'=>'MADITHAME', 'area_officer'=>'LEBOGANG', 'group_name'=>'THUSHANANG', 'created_at'=>'2022-05-22'],
            ['centre_name'=>'MADITHAME', 'area_officer'=>'LEBOGANG', 'group_name'=>'BOKAMOSO', 'created_at'=>'2022-05-22'],
            ['centre_name'=>'MADITHAME', 'area_officer'=>'LEBOGANG', 'group_name'=>'RUTANANG', 'created_at'=>'2022-04-22'],
            ['centre_name'=>'MADITHAME', 'area_officer'=>'LEBOGANG', 'group_name'=>'RUTANANG-2', 'created_at'=>'2022-08-22'],
            ['centre_name'=>'MADITHAME', 'area_officer'=>'LEBOGANG', 'group_name'=>'REATLEGILE', 'created_at'=>'2022-05-22'],
            ['centre_name'=>'MADITHAME', 'area_officer'=>'LEBOGANG', 'group_name'=>'KATLEGO', 'created_at'=>'2022-05-22'],
            ['centre_name'=>'MADITHAME', 'area_officer'=>'LEBOGANG', 'group_name'=>'BOITSHEPO', 'created_at'=>'2022-05-22'],
            ['centre_name'=>'MADITHAME', 'area_officer'=>'LEBOGANG', 'group_name'=>'REKA KGONA', 'created_at'=>'2022-05-22'],
            ['centre_name'=>'MADITHAME', 'area_officer'=>'LEBOGANG', 'group_name'=>'BAIPOTI', 'created_at'=>'2022-06-22'],
            ['centre_name'=>'MADITHAME', 'area_officer'=>'LEBOGANG', 'group_name'=>'BOPHELO', 'created_at'=>'2022-08-22'],
            ['centre_name'=>'MADITHAME', 'area_officer'=>'LEBOGANG', 'group_name'=>'MAPOTENG', 'created_at'=>'2022-08-22'],
            ['centre_name'=>'MPHANAMA', 'area_officer'=>'LEBOGANG', 'group_name'=>'HLAPOGADI', 'created_at'=>'2022-06-22'],
            ['centre_name'=>'MPHANAMA', 'area_officer'=>'LEBOGANG', 'group_name'=>'KGATELOPELE', 'created_at'=>'2022-06-22'],
            ['centre_name'=>'MPHANAMA', 'area_officer'=>'LEBOGANG', 'group_name'=>'REBONE', 'created_at'=>'2022-06-22'],
            ['centre_name'=>'MPHANAMA', 'area_officer'=>'LEBOGANG', 'group_name'=>'NATSWANA', 'created_at'=>'2022-05-22'],
            ['centre_name'=>'MPHANAMA', 'area_officer'=>'LEBOGANG', 'group_name'=>'MAPUWE', 'created_at'=>'2022-06-22'],
            ['centre_name'=>'PELANGWE', 'area_officer'=>'LEBOGANG', 'group_name'=>'BOHLALE', 'created_at'=>'2022-06-22'],
            ['centre_name'=>'PELANGWE', 'area_officer'=>'LEBOGANG', 'group_name'=>'SKEEMSAAM', 'created_at'=>'2022-06-22'],
            ['centre_name'=>'PELANGWE', 'area_officer'=>'LEBOGANG', 'group_name'=>'BOLOBA', 'created_at'=>'2022-06-22'],
            ['centre_name'=>'PELANGWE', 'area_officer'=>'LEBOGANG', 'group_name'=>'LULU MOUNTAIN', 'created_at'=>'2022-06-22'],
            ['centre_name'=>'PELANGWE', 'area_officer'=>'LEBOGANG', 'group_name'=>'PHAANE', 'created_at'=>'2022-06-22'],
            ['centre_name'=>'PELANGWE', 'area_officer'=>'LEBOGANG', 'group_name'=>'LERATO', 'created_at'=>'2022-07-22'],
            ['centre_name'=>'TLAKALENCHABELENG', 'area_officer'=>'LEBOGANG', 'group_name'=>'TSWELOPELE', 'created_at'=>'2022-06-22'],
            ['centre_name'=>'TLAKALENCHABELENG', 'area_officer'=>'LEBOGANG', 'group_name'=>'LETHABO', 'created_at'=>'2022-06-22'],
            ['centre_name'=>'TLAKALENCHABELENG', 'area_officer'=>'LEBOGANG', 'group_name'=>'FAHLOLOGANG', 'created_at'=>'2022-06-22'],
            ['centre_name'=>'TLAKALENCHABELENG', 'area_officer'=>'LEBOGANG', 'group_name'=>'AGANANG', 'created_at'=>'2022-06-22'],
            ['centre_name'=>'TLAKALENCHABELENG', 'area_officer'=>'LEBOGANG', 'group_name'=>'BAITSHEPHI', 'created_at'=>'2022-08-22'],
            ['centre_name'=>'GLOBAL', 'area_officer'=>'LEBOGANG', 'group_name'=>'MAPOTENG', 'created_at'=>'2022-07-22'],
            ['centre_name'=>'GLOBAL', 'area_officer'=>'LEBOGANG', 'group_name'=>'TSOGANG', 'created_at'=>'2022-07-22'],
            ['centre_name'=>'GLOBAL', 'area_officer'=>'LEBOGANG', 'group_name'=>'THUSHANANG', 'created_at'=>'2022-07-22'],
            ['centre_name'=>'GLOBAL', 'area_officer'=>'LEBOGANG', 'group_name'=>'BA LERATO', 'created_at'=>'2022-07-22'],
            ['centre_name'=>'EMHLANGENI', 'area_officer'=>'LOUIS', 'group_name'=>'SIYATHUTHUKA', 'created_at'=>'2022-07-22'],
            ['centre_name'=>'EMHLANGENI', 'area_officer'=>'LOUIS', 'group_name'=>'UMENATHI', 'created_at'=>'2022-05-22'],
            ['centre_name'=>'EMHLANGENI', 'area_officer'=>'LOUIS', 'group_name'=>'MASIMBONGE', 'created_at'=>'2022-06-22'],
            ['centre_name'=>'EMHLANGENI', 'area_officer'=>'LOUIS', 'group_name'=>'SIYAPHAMBILI', 'created_at'=>'2022-07-22'],
            ['centre_name'=>'VILAMAHLO', 'area_officer'=>'LOUIS', 'group_name'=>'LINDOKUHLE', 'created_at'=>'2022-04-22'],
            ['centre_name'=>'VILAMAHLO', 'area_officer'=>'LOUIS', 'group_name'=>'STHEMBELE', 'created_at'=>'2022-04-22'],
            ['centre_name'=>'VILAMAHLO', 'area_officer'=>'LOUIS', 'group_name'=>'INTOBEKO', 'created_at'=>'2022-05-22'],
            ['centre_name'=>'VILAMAHLO', 'area_officer'=>'LOUIS', 'group_name'=>'SIZAKANCANE', 'created_at'=>'2022-04-22'],
            ['centre_name'=>'VILAMAHLO', 'area_officer'=>'LOUIS', 'group_name'=>'SINAKEKELE', 'created_at'=>'2022-06-22'],
            ['centre_name'=>'ZICOLE', 'area_officer'=>'LOUIS', 'group_name'=>'MASIBUMBANE', 'created_at'=>'2022-02-22'],
            ['centre_name'=>'ZICOLE', 'area_officer'=>'LOUIS', 'group_name'=>'MSENI', 'created_at'=>'2022-04-22'],
            ['centre_name'=>'ZICOLE', 'area_officer'=>'LOUIS', 'group_name'=>'SIYAPHUMELELA', 'created_at'=>'2022-05-22'],
            ['centre_name'=>'ZICOLE', 'area_officer'=>'LOUIS', 'group_name'=>'HLAKANIPHANI', 'created_at'=>'2022-05-22'],
            ['centre_name'=>'ZICOLE', 'area_officer'=>'LOUIS', 'group_name'=>'SIYAZANA 2', 'created_at'=>'2022-05-22'],
            ['centre_name'=>'ZICOLE', 'area_officer'=>'LOUIS', 'group_name'=>'SIYAZAMA 1', 'created_at'=>'2022-06-22'],
            ['centre_name'=>'ZICOLE', 'area_officer'=>'LOUIS', 'group_name'=>'SIYATHUTHUKA', 'created_at'=>'2022-06-22'],
            ['centre_name'=>'ZICOLE', 'area_officer'=>'LOUIS', 'group_name'=>'PHIWOKUHLE', 'created_at'=>'2022-07-22'],
            ['centre_name'=>'NDLANGAMANDLA', 'area_officer'=>'LOUIS', 'group_name'=>'VUKUZITHATHE', 'created_at'=>'2022-05-22'],
            ['centre_name'=>'NDLANGAMANDLA', 'area_officer'=>'LOUIS', 'group_name'=>'SINETHEMBA', 'created_at'=>'2022-04-22'],
            ['centre_name'=>'NDLANGAMANDLA', 'area_officer'=>'LOUIS', 'group_name'=>'SIYATHUTHUKA', 'created_at'=>'2022-05-22'],
            ['centre_name'=>'NDLANGAMANDLA', 'area_officer'=>'LOUIS', 'group_name'=>'SIYAZAMA', 'created_at'=>'2022-07-22'],
            ['centre_name'=>'NHLALAKAHLE', 'area_officer'=>'LOUIS', 'group_name'=>'SIYAZAMA', 'created_at'=>'2022-06-22'],
            ['centre_name'=>'NHLALAKAHLE', 'area_officer'=>'LOUIS', 'group_name'=>'IMPUMELELO', 'created_at'=>'2022-06-22'],
            ['centre_name'=>'NHLALAKAHLE', 'area_officer'=>'LOUIS', 'group_name'=>'SIYATHUTHUKA', 'created_at'=>'2022-06-22'],
            ['centre_name'=>'NHLALAKAHLE', 'area_officer'=>'LOUIS', 'group_name'=>'THUTHUKANI', 'created_at'=>'2022-06-22'],
            ['centre_name'=>'NHLALAKAHLE', 'area_officer'=>'LOUIS', 'group_name'=>'INTOKOZO', 'created_at'=>'2022-06-22'],
            ['centre_name'=>'NHLALAKAHLE', 'area_officer'=>'LOUIS', 'group_name'=>'BAMBANANI', 'created_at'=>'2022-07-22'],
            ['centre_name'=>'NHLALAKAHLE', 'area_officer'=>'LOUIS', 'group_name'=>'QOAQNQNI', 'created_at'=>'2022-08-22'],
            ['centre_name'=>'NHLALAKAHLE', 'area_officer'=>'LOUIS', 'group_name'=>'ANDILE', 'created_at'=>'2022-08-22'],
            ['centre_name'=>'NHLALAKAHLE', 'area_officer'=>'LOUIS', 'group_name'=>'ZAMIMPILO', 'created_at'=>'2022-08-22'],
            ['centre_name'=>'NHLALAKAHLE', 'area_officer'=>'LOUIS', 'group_name'=>'SIYANQOBA', 'created_at'=>'2022-08-22'],
            ['centre_name'=>'NHLALAKAHLE', 'area_officer'=>'LOUIS', 'group_name'=>'ASAKHANE', 'created_at'=>'2022-08-22'],
            ['centre_name'=>'NKONGOLWANA', 'area_officer'=>'LOUIS', 'group_name'=>'ITHUBALETHU', 'created_at'=>'2022-06-22'],
            ['centre_name'=>'NKONGOLWANA', 'area_officer'=>'LOUIS', 'group_name'=>'ZAKHELA', 'created_at'=>'2022-06-22'],
            ['centre_name'=>'NKONGOLWANA', 'area_officer'=>'LOUIS', 'group_name'=>'SIYAXHASANA', 'created_at'=>'2022-06-22'],
            ['centre_name'=>'NKONGOLWANA', 'area_officer'=>'LOUIS', 'group_name'=>'JUSTICE', 'created_at'=>'2022-06-22'],
            ['centre_name'=>'NKONGOLWANA', 'area_officer'=>'LOUIS', 'group_name'=>'SIYAKHULA', 'created_at'=>'2022-06-22'],
            ['centre_name'=>'UMBUMBANO', 'area_officer'=>'LOUIS', 'group_name'=>'MASIBUMBANE', 'created_at'=>'2022-05-22'],
            ['centre_name'=>'UMBUMBANO', 'area_officer'=>'LOUIS', 'group_name'=>'KHEBHALI', 'created_at'=>'2022-05-22'],
            ['centre_name'=>'UMBUMBANO', 'area_officer'=>'LOUIS', 'group_name'=>'SIHLANGANE', 'created_at'=>'2022-05-22'],
            ['centre_name'=>'UMBUMBANO', 'area_officer'=>'LOUIS', 'group_name'=>'IMBEWEHLE', 'created_at'=>'2022-05-22'],
            ['centre_name'=>'UMBUMBANO', 'area_officer'=>'LOUIS', 'group_name'=>'ROSES', 'created_at'=>'2022-05-22'],
            ['centre_name'=>'UMBUMBANO', 'area_officer'=>'LOUIS', 'group_name'=>'SIZAKAHLE', 'created_at'=>'2022-05-22'],
            ['centre_name'=>'UMBUMBANO', 'area_officer'=>'LOUIS', 'group_name'=>'SIYABULELA', 'created_at'=>'2022-05-22'],
            ['centre_name'=>'UMBUMBANO', 'area_officer'=>'LOUIS', 'group_name'=>'SIYATHANDANA', 'created_at'=>'2022-05-22'],
            ['centre_name'=>'UMBUMBANO', 'area_officer'=>'LOUIS', 'group_name'=>'THEMBELIHLE', 'created_at'=>'2022-05-22'],
            ['centre_name'=>'UMBUMBANO', 'area_officer'=>'LOUIS', 'group_name'=>'THREE SISTERS', 'created_at'=>'2022-06-22'],
            ['centre_name'=>'UMBUMBANO', 'area_officer'=>'LOUIS', 'group_name'=>'UKUKHANYA', 'created_at'=>'2022-06-22'],
            ['centre_name'=>'UMBUMBANO', 'area_officer'=>'LOUIS', 'group_name'=>'INHLOSENHLE', 'created_at'=>'2022-06-22'],
            ['centre_name'=>'QUEQUE1', 'area_officer'=>'POTEGO', 'group_name'=>'SICELUTHANDO', 'created_at'=>'2022-05-22'],
            ['centre_name'=>'QUEQUE1', 'area_officer'=>'POTEGO', 'group_name'=>'JABULANI', 'created_at'=>'2022-05-22'],
            ['centre_name'=>'QUEQUE1', 'area_officer'=>'POTEGO', 'group_name'=>'LANGELIHLE', 'created_at'=>'2022-05-22'],
            ['centre_name'=>'QUEQUE1', 'area_officer'=>'POTEGO', 'group_name'=>'PICK IT UP', 'created_at'=>'2022-05-22'],
            ['centre_name'=>'QUEQUE2', 'area_officer'=>'POTEGO', 'group_name'=>'SIYAKHULA', 'created_at'=>'2022-07-22'],
            ['centre_name'=>'QUEQUE2', 'area_officer'=>'POTEGO', 'group_name'=>'SIYAZAMA', 'created_at'=>'2022-06-22'],
            ['centre_name'=>'QUEQUE2', 'area_officer'=>'POTEGO', 'group_name'=>'VUKUZENZELE', 'created_at'=>'2022-08-22'],
            ['centre_name'=>'PHUMLANI', 'area_officer'=>'POTEGO', 'group_name'=>'THUBALETHU', 'created_at'=>'2022-05-22'],
            ['centre_name'=>'PHUMLANI', 'area_officer'=>'POTEGO', 'group_name'=>'SIBONELO', 'created_at'=>'2022-05-22'],
            ['centre_name'=>'PHUMLANI', 'area_officer'=>'POTEGO', 'group_name'=>'SIYAPHAMBILI', 'created_at'=>'2022-05-22'],
            ['centre_name'=>'PHUMLANI', 'area_officer'=>'POTEGO', 'group_name'=>'QODISANI', 'created_at'=>'2022-05-22'],
            ['centre_name'=>'PHUMLANI', 'area_officer'=>'POTEGO', 'group_name'=>'ISANDLASOMUSA', 'created_at'=>'2022-05-22'],
            ['centre_name'=>'PHUMLANI', 'area_officer'=>'POTEGO', 'group_name'=>'SENZAKAHLE', 'created_at'=>'2022-05-22'],
            ['centre_name'=>'PHUMLANI', 'area_officer'=>'POTEGO', 'group_name'=>'LINDAKAHLE', 'created_at'=>'2022-06-22'],
            ['centre_name'=>'MXHASHONI', 'area_officer'=>'POTEGO', 'group_name'=>'SIYAZAMA', 'created_at'=>'2022-05-22'],
            ['centre_name'=>'MXHASHONI', 'area_officer'=>'POTEGO', 'group_name'=>'NKOSINOMUSA', 'created_at'=>'2022-05-22'],
            ['centre_name'=>'MXHASHONI', 'area_officer'=>'POTEGO', 'group_name'=>'ISPHAMANDLA', 'created_at'=>'2022-05-22'],
            ['centre_name'=>'SOPHIA', 'area_officer'=>'POTEGO', 'group_name'=>'ESIHLE', 'created_at'=>'2022-06-22'],
            ['centre_name'=>'SOPHIA', 'area_officer'=>'POTEGO', 'group_name'=>'ZENZELE', 'created_at'=>'2022-06-22'],
            ['centre_name'=>'SOPHIA', 'area_officer'=>'POTEGO', 'group_name'=>'THUTHUKANI', 'created_at'=>'2022-06-22'],
            ['centre_name'=>'SOPHIA', 'area_officer'=>'POTEGO', 'group_name'=>'JWAYELANE', 'created_at'=>'2022-06-22'],
            ['centre_name'=>'SOPHIA', 'area_officer'=>'POTEGO', 'group_name'=>'ATHANDWA', 'created_at'=>'2022-06-22'],
            ['centre_name'=>'SOPHIA', 'area_officer'=>'POTEGO', 'group_name'=>'ASIPHE', 'created_at'=>'2022-06-22'],
            ['centre_name'=>'NTABABOMVU', 'area_officer'=>'POTEGO', 'group_name'=>'THANDOLETHU', 'created_at'=>'2022-06-22'],
            ['centre_name'=>'NTABABOMVU', 'area_officer'=>'POTEGO', 'group_name'=>'SIYAZAMA', 'created_at'=>'2022-06-22'],
            ['centre_name'=>'NTABABOMVU', 'area_officer'=>'POTEGO', 'group_name'=>'THREE WOMEN CLUB', 'created_at'=>'2022-06-22'],
            ['centre_name'=>'NTABABOMVU', 'area_officer'=>'POTEGO', 'group_name'=>'SIYACATHULA', 'created_at'=>'2022-06-22'],
            ['centre_name'=>'NTABABOMVU', 'area_officer'=>'POTEGO', 'group_name'=>'BUHLEBUYEZA', 'created_at'=>'2022-06-22'],
            ['centre_name'=>'BLAAUBOSH', 'area_officer'=>'THABILE', 'group_name'=>'PHILISANI', 'created_at'=>'2022-07-22'],
            ['centre_name'=>'BLAAUBOSH', 'area_officer'=>'THABILE', 'group_name'=>'THUTHUKANI', 'created_at'=>'2022-07-22'],
            ['centre_name'=>'BLAAUBOSH', 'area_officer'=>'THABILE', 'group_name'=>'MASIBAMBISANE', 'created_at'=>'2022-07-22'],
            ['centre_name'=>'BLAAUBOSH', 'area_officer'=>'THABILE', 'group_name'=>'MASISIZANE', 'created_at'=>'2022-03-22'],
            ['centre_name'=>'BLAAUBOSH', 'area_officer'=>'THABILE', 'group_name'=>'SISONKE', 'created_at'=>'2022-04-22'],
            ['centre_name'=>'BLAAUBOSH', 'area_officer'=>'THABILE', 'group_name'=>'SISONKE-2', 'created_at'=>'2022-08-22'],
            ['centre_name'=>'BLAAUBOSH', 'area_officer'=>'THABILE', 'group_name'=>'NHLOSOKUHLE', 'created_at'=>'2022-02-22'],
            ['centre_name'=>'BLAAUBOSH', 'area_officer'=>'THABILE', 'group_name'=>'NHLOSOKUHLE-2', 'created_at'=>'2022-08-22'],
            ['centre_name'=>'DICKS', 'area_officer'=>'THABILE', 'group_name'=>'AMADLELO', 'created_at'=>'2022-07-22'],
            ['centre_name'=>'DICKS', 'area_officer'=>'THABILE', 'group_name'=>'MINI ENHLE', 'created_at'=>'2022-03-22'],
            ['centre_name'=>'DICKS', 'area_officer'=>'THABILE', 'group_name'=>'SINOTHILE', 'created_at'=>'2022-07-22'],
            ['centre_name'=>'DICKS', 'area_officer'=>'THABILE', 'group_name'=>'ZANOKUHLE', 'created_at'=>'2022-04-22'],
            ['centre_name'=>'DICKS', 'area_officer'=>'THABILE', 'group_name'=>'ZANOKUHLE-2', 'created_at'=>'2022-08-22'],
            ['centre_name'=>'MNDOZO', 'area_officer'=>'THABILE', 'group_name'=>'ICEBOLETHU', 'created_at'=>'2022-02-22'],
            ['centre_name'=>'MNDOZO', 'area_officer'=>'THABILE', 'group_name'=>'ICEBOLETHU-2', 'created_at'=>'2022-08-22'],
            ['centre_name'=>'MNDOZO', 'area_officer'=>'THABILE', 'group_name'=>'NKULULEKO', 'created_at'=>'2022-06-22'],
            ['centre_name'=>'MNDOZO', 'area_officer'=>'THABILE', 'group_name'=>'FELLOWSHIP', 'created_at'=>'2022-06-22'],
            ['centre_name'=>'MNDOZO', 'area_officer'=>'THABILE', 'group_name'=>'SYASEBENZA', 'created_at'=>'2022-05-22'],
            ['centre_name'=>'MNDOZO', 'area_officer'=>'THABILE', 'group_name'=>'INKAZIMULO', 'created_at'=>'2022-08-22'],
            ['centre_name'=>'NTSIMBINI', 'area_officer'=>'THABILE', 'group_name'=>'IMPUMELELO', 'created_at'=>'2022-03-22'],
            ['centre_name'=>'NTSIMBINI', 'area_officer'=>'THABILE', 'group_name'=>'INDINGO', 'created_at'=>'2022-07-22'],
            ['centre_name'=>'NTSIMBINI', 'area_officer'=>'THABILE', 'group_name'=>'UBUMBANO', 'created_at'=>'2022-03-22'],
            ['centre_name'=>'NTSIMBINI', 'area_officer'=>'THABILE', 'group_name'=>'HLELOKWAZI', 'created_at'=>'2022-04-22'],
            ['centre_name'=>'NTSIMBINI', 'area_officer'=>'THABILE', 'group_name'=>'UNCEDOLWEMPILO', 'created_at'=>'2022-05-22'],
            ['centre_name'=>'NTSIMBINI', 'area_officer'=>'THABILE', 'group_name'=>'ISIPHUMELELE', 'created_at'=>'2022-05-22'],
            ['centre_name'=>'NTSIMBINI', 'area_officer'=>'THABILE', 'group_name'=>'ICEBOLETHU', 'created_at'=>'2022-04-22'],
            ['centre_name'=>'NTSIMBINI', 'area_officer'=>'THABILE', 'group_name'=>'ICEBOLETHU-2', 'created_at'=>'2022-08-22'],
            ['centre_name'=>'NTSIMBINI', 'area_officer'=>'THABILE', 'group_name'=>'NHLOSOKUHLE', 'created_at'=>'2022-08-22'],
            ['centre_name'=>'NYONINI', 'area_officer'=>'THABILE', 'group_name'=>'IMPILO', 'created_at'=>'2022-02-22'],
            ['centre_name'=>'NYONINI', 'area_officer'=>'THABILE', 'group_name'=>'IMPILO-2', 'created_at'=>'2022-08-22'],
            ['centre_name'=>'NYONINI', 'area_officer'=>'THABILE', 'group_name'=>'ISIQALO', 'created_at'=>'2022-02-22'],
            ['centre_name'=>'NYONINI', 'area_officer'=>'THABILE', 'group_name'=>'ISIQALO-2', 'created_at'=>'2022-08-22'],
            ['centre_name'=>'SENZOKUHLE', 'area_officer'=>'THABILE', 'group_name'=>'THEMBA', 'created_at'=>'2022-07-22'],
            ['centre_name'=>'SENZOKUHLE', 'area_officer'=>'THABILE', 'group_name'=>'ZANOKUHLE', 'created_at'=>'2022-07-22'],
            ['centre_name'=>'SENZOKUHLE', 'area_officer'=>'THABILE', 'group_name'=>'ZAMAZAMA', 'created_at'=>'2022-05-22'],
            ['centre_name'=>'SENZOKUHLE', 'area_officer'=>'THABILE', 'group_name'=>'MASIBAMBANE', 'created_at'=>'2022-05-22'],
            ['centre_name'=>'SENZOKUHLE', 'area_officer'=>'THABILE', 'group_name'=>'OKWETHUSONDWA', 'created_at'=>'2022-06-22'],
            ['centre_name'=>'SENZOKUHLE', 'area_officer'=>'THABILE', 'group_name'=>'DREAM TEAM', 'created_at'=>'2022-06-22'],
            ['centre_name'=>'SENZOKUHLE', 'area_officer'=>'THABILE', 'group_name'=>'SUKUMANE', 'created_at'=>'2022-07-22'],
            ['centre_name'=>'SGODIPHOLA', 'area_officer'=>'THABILE', 'group_name'=>'VUKASAKHE', 'created_at'=>'2022-03-22'],
            ['centre_name'=>'SGODIPHOLA', 'area_officer'=>'THABILE', 'group_name'=>'VUKUZENZELE', 'created_at'=>'2022-03-22'],
            ['centre_name'=>'SGODIPHOLA', 'area_officer'=>'THABILE', 'group_name'=>'KHETHOKUHLE', 'created_at'=>'2022-05-22'],
            ['centre_name'=>'SGODIPHOLA', 'area_officer'=>'THABILE', 'group_name'=>'BAMBANANI', 'created_at'=>'2022-08-22'],
            ['centre_name'=>'SGODIPHOLA', 'area_officer'=>'THABILE', 'group_name'=>'SYAPHUMELELA', 'created_at'=>'2022-08-22'],
            ['centre_name'=>'MSOMI', 'area_officer'=>'THABILE', 'group_name'=>'ZIBAMBELENI', 'created_at'=>'2022-07-21'],
            ['centre_name'=>'DUBAI', 'area_officer'=>'THABILE', 'group_name'=>'SYAMUKELA', 'created_at'=>'2022-07-22'],
            ['centre_name'=>'DUBAI', 'area_officer'=>'THABILE', 'group_name'=>'VULAMEHLO', 'created_at'=>'2022-07-22'],
            ['centre_name'=>'DUBAI', 'area_officer'=>'THABILE', 'group_name'=>'SYAZAMA GROUP', 'created_at'=>'2022-05-22'],
            ['centre_name'=>'DUBAI', 'area_officer'=>'THABILE', 'group_name'=>'LINDA', 'created_at'=>'2022-05-22'],
            ['centre_name'=>'DUBAI', 'area_officer'=>'THABILE', 'group_name'=>'SYASEBENZA', 'created_at'=>'2022-06-22'],
            ['centre_name'=>'DUBAI', 'area_officer'=>'THABILE', 'group_name'=>'SPHIWE', 'created_at'=>'2022-06-22'],
            ['centre_name'=>'UMBUMBANO', 'area_officer'=>'THABILE', 'group_name'=>'SYATHUTHUKA', 'created_at'=>'2022-05-22'],
            ['centre_name'=>'UMBUMBANO', 'area_officer'=>'THABILE', 'group_name'=>'SIZAKANCANE', 'created_at'=>'2022-05-22'],
            ['centre_name'=>'UMBUMBANO', 'area_officer'=>'THABILE', 'group_name'=>'ZIBAMBELENI', 'created_at'=>'2022-05-22'],
            ['centre_name'=>'UMBUMBANO', 'area_officer'=>'THABILE', 'group_name'=>'ZAMANI', 'created_at'=>'2022-05-22'],
            ['centre_name'=>'UMBUMBANO', 'area_officer'=>'THABILE', 'group_name'=>'SENZOKWETHU', 'created_at'=>'2022-08-22'],
            ['centre_name'=>'UMBUMBANO', 'area_officer'=>'THABILE', 'group_name'=>'ZAMOKUHLE', 'created_at'=>'2022-08-22'],
            ['centre_name'=>'KOPARASI', 'area_officer'=>'THABILE', 'group_name'=>'QALAKANCANE', 'created_at'=>'2022-07-22'],
            ['centre_name'=>'KOPARASI', 'area_officer'=>'THABILE', 'group_name'=>'VUKUZENZELE', 'created_at'=>'2022-06-22'],
            ['centre_name'=>'KOPARASI', 'area_officer'=>'THABILE', 'group_name'=>'THANDOLWETHU', 'created_at'=>'2022-06-22'],
            ['centre_name'=>'KOPARASI', 'area_officer'=>'THABILE', 'group_name'=>'PHEMBOKUHLE', 'created_at'=>'2022-04-22'],
            ['centre_name'=>'KOPARASI', 'area_officer'=>'THABILE', 'group_name'=>'SIBATHATHU', 'created_at'=>'2022-04-22'],
            ['centre_name'=>'KOPARASI', 'area_officer'=>'THABILE', 'group_name'=>'SIBATHATHU-2', 'created_at'=>'2022-08-22'],
            ['centre_name'=>'KOPARASI', 'area_officer'=>'THABILE', 'group_name'=>'IMPILOYAQHUBEKA', 'created_at'=>'2022-08-22'],
            ['centre_name'=>'KOPARASI', 'area_officer'=>'THABILE', 'group_name'=>'SIZAKANCANE', 'created_at'=>'2022-02-22'],
            ['centre_name'=>'KOPARASI', 'area_officer'=>'THABILE', 'group_name'=>'SIZAKANCANE-2', 'created_at'=>'2022-08-22'],
            ['centre_name'=>'KOPARASI', 'area_officer'=>'THABILE', 'group_name'=>'INQANAWE', 'created_at'=>'2022-02-22'],
            ['centre_name'=>'KOPARASI', 'area_officer'=>'THABILE', 'group_name'=>'INQANAWE-2', 'created_at'=>'2022-08-22'],
            ['centre_name'=>'KOPARASI', 'area_officer'=>'THABILE', 'group_name'=>'ISQALOSOMPILO', 'created_at'=>'2022-06-22'],
            ['centre_name'=>'KHETHUKTHULA', 'area_officer'=>'THABILE', 'group_name'=>'IMPUMELELO', 'created_at'=>'2022-07-22'],
            ['centre_name'=>'KHETHUKTHULA', 'area_officer'=>'THABILE', 'group_name'=>'SIYANQOBA', 'created_at'=>'2022-05-22'],
            ['centre_name'=>'KHETHUKTHULA', 'area_officer'=>'THABILE', 'group_name'=>'SIYANQODA', 'created_at'=>'2022-07-22'],
            ['centre_name'=>'KHETHUKTHULA', 'area_officer'=>'THABILE', 'group_name'=>'BUMBANANI', 'created_at'=>'2022-05-22'],
            ['centre_name'=>'KHETHUKTHULA', 'area_officer'=>'THABILE', 'group_name'=>'SIZIMELE', 'created_at'=>'2022-07-22'],
            ['centre_name'=>'KHETHUKTHULA', 'area_officer'=>'THABILE', 'group_name'=>'ZITHUTHUKISE', 'created_at'=>'2022-04-22'],
            ['centre_name'=>'KHETHUKTHULA', 'area_officer'=>'THABILE', 'group_name'=>'ZITHUTHUKISE-2', 'created_at'=>'2022-08-22'],
            ['centre_name'=>'LONG HOMES', 'area_officer'=>'THABILE', 'group_name'=>'NDABEZINHLE', 'created_at'=>'2022-07-22'],
            ['centre_name'=>'LONG HOMES', 'area_officer'=>'THABILE', 'group_name'=>'ZITHUTHUKISE', 'created_at'=>'2022-02-22'],
            ['centre_name'=>'LONG HOMES', 'area_officer'=>'THABILE', 'group_name'=>'ZITHUTHUKISE-2', 'created_at'=>'2022-08-22'],
            ['centre_name'=>'LONG HOMES', 'area_officer'=>'THABILE', 'group_name'=>'KHETHOKUHLE', 'created_at'=>'2022-04-22'],
            ['centre_name'=>'LONG HOMES', 'area_officer'=>'THABILE', 'group_name'=>'KHETHOKUHLE-2', 'created_at'=>'2022-08-22'],
            ['centre_name'=>'LONG HOMES', 'area_officer'=>'THABILE', 'group_name'=>'GENESIS', 'created_at'=>'2022-04-22'],
            ['centre_name'=>'LONG HOMES', 'area_officer'=>'THABILE', 'group_name'=>'GENESIS-2', 'created_at'=>'2022-08-22'],
            ['centre_name'=>'LONG HOMES', 'area_officer'=>'THABILE', 'group_name'=>'EYETHU', 'created_at'=>'2022-04-22'],
            ['centre_name'=>'LONG HOMES', 'area_officer'=>'THABILE', 'group_name'=>'EYETHU-2', 'created_at'=>'2022-08-22'],
            ['centre_name'=>'LONG HOMES', 'area_officer'=>'THABILE', 'group_name'=>'SIMUNYE', 'created_at'=>'2022-04-22'],
            ['centre_name'=>'LONG HOMES', 'area_officer'=>'THABILE', 'group_name'=>'SINOTHANDO', 'created_at'=>'2022-04-22'],
            ['centre_name'=>'LONG HOMES', 'area_officer'=>'THABILE', 'group_name'=>'SINOTHANDO-2', 'created_at'=>'2022-08-22'],
            ['centre_name'=>'LONG HOMES', 'area_officer'=>'THABILE', 'group_name'=>'VULAMENHLO', 'created_at'=>'2022-07-22'],
            ['centre_name'=>'LONG HOMES', 'area_officer'=>'THABILE', 'group_name'=>'SIPHEPHILE', 'created_at'=>'2022-06-22'],
            ['centre_name'=>'MATHANGENI', 'area_officer'=>'THABILE', 'group_name'=>'MASICATHULISANE', 'created_at'=>'2022-07-22'],
            ['centre_name'=>'MATHANGENI', 'area_officer'=>'THABILE', 'group_name'=>'THUBELIHLE', 'created_at'=>'2022-07-22'],
            ['centre_name'=>'MATHANGENI', 'area_officer'=>'THABILE', 'group_name'=>'UBUMBANO', 'created_at'=>'2022-02-22'],
            ['centre_name'=>'MATHANGENI', 'area_officer'=>'THABILE', 'group_name'=>'UBUMBANO-2', 'created_at'=>'2022-08-22'],
            ['centre_name'=>'MATHANGENI', 'area_officer'=>'THABILE', 'group_name'=>'MASAKHANE', 'created_at'=>'2022-05-22'],
            ['centre_name'=>'MATHANGENI', 'area_officer'=>'THABILE', 'group_name'=>'THEMBELISHA', 'created_at'=>'2022-05-22'],
            ['centre_name'=>'MATHANGENI', 'area_officer'=>'THABILE', 'group_name'=>'ICEBOLIHLE', 'created_at'=>'2022-07-22'],
            ['centre_name'=>'VULINDLELA', 'area_officer'=>'THABILE', 'group_name'=>'MELOKUHLE', 'created_at'=>'2022-06-22'],
            ['centre_name'=>'VULINDLELA', 'area_officer'=>'THABILE', 'group_name'=>'ZAMOKUHLE', 'created_at'=>'2022-06-22'],
            ['centre_name'=>'VULINDLELA', 'area_officer'=>'THABILE', 'group_name'=>'SMUNYE', 'created_at'=>'2022-06-22'],
            ['centre_name'=>'SUKUMANI', 'area_officer'=>'NALEDI', 'group_name'=>'BUHLEBUYEZA', 'created_at'=>'2022-02-22'],
            ['centre_name'=>'SUKUMANI', 'area_officer'=>'NALEDI', 'group_name'=>'BUHLEBUYEZA-2', 'created_at'=>'2022-08-22'],
            ['centre_name'=>'SUKUMANI', 'area_officer'=>'NALEDI', 'group_name'=>'SINOTHILE', 'created_at'=>'2022-07-22'],
            ['centre_name'=>'SUKUMANI', 'area_officer'=>'NALEDI', 'group_name'=>'SIYASEBENZA', 'created_at'=>'2022-07-22'],
            ['centre_name'=>'SUKUMANI', 'area_officer'=>'NALEDI', 'group_name'=>'SYAVUKA', 'created_at'=>'2022-05-22'],
            ['centre_name'=>'SUKUMANI', 'area_officer'=>'NALEDI', 'group_name'=>'NTOBEKO', 'created_at'=>'2022-05-22'],
            ['centre_name'=>'SECTION 7', 'area_officer'=>'NALEDI', 'group_name'=>'ANGELS', 'created_at'=>'2022-03-22'],
            ['centre_name'=>'SECTION 7', 'area_officer'=>'NALEDI', 'group_name'=>'GOD NEVER FAILS', 'created_at'=>'2022-07-22'],
            ['centre_name'=>'SECTION 7', 'area_officer'=>'NALEDI', 'group_name'=>'HLANGANANI', 'created_at'=>'2022-05-22'],
            ['centre_name'=>'SECTION 7', 'area_officer'=>'NALEDI', 'group_name'=>'SQALIMPILO', 'created_at'=>'2022-06-22'],
            ['centre_name'=>'SECTION 7', 'area_officer'=>'NALEDI', 'group_name'=>'SAKHISIZWE', 'created_at'=>'2022-06-22'],
            ['centre_name'=>'SECTION 7', 'area_officer'=>'NALEDI', 'group_name'=>'MASAKHANE', 'created_at'=>'2022-06-22'],
            ['centre_name'=>'SIYAPHAMBILI', 'area_officer'=>'NALEDI', 'group_name'=>'IMPILO', 'created_at'=>'2022-08-22'],
            ['centre_name'=>'SIYAPHAMBILI', 'area_officer'=>'NALEDI', 'group_name'=>'PHIWOKUHLE', 'created_at'=>'2022-08-22'],
            ['centre_name'=>'THUBELIHLE', 'area_officer'=>'PHUMZILE', 'group_name'=>'BAMBANANI', 'created_at'=>'2022-05-22'],
            ['centre_name'=>'THUBELIHLE', 'area_officer'=>'PHUMZILE', 'group_name'=>'QHUBEKANI', 'created_at'=>'2022-05-22'],
            ['centre_name'=>'THUBELIHLE', 'area_officer'=>'PHUMZILE', 'group_name'=>'SNETHEMBA', 'created_at'=>'2022-05-22'],
            ['centre_name'=>'THUBELIHLE', 'area_officer'=>'PHUMZILE', 'group_name'=>'SIYATHUTHUKA', 'created_at'=>'2022-05-22'],
            ['centre_name'=>'THUBELIHLE', 'area_officer'=>'PHUMZILE', 'group_name'=>'IMPUMELELO', 'created_at'=>'2022-08-22'],
            ['centre_name'=>'THUBELIHLE', 'area_officer'=>'PHUMZILE', 'group_name'=>'HLANZEKO', 'created_at'=>'2022-08-22'],
            ['centre_name'=>'ZAMOKUNZEZELA', 'area_officer'=>'PHUMZILE', 'group_name'=>'SIYATHUTHUKA', 'created_at'=>'2022-05-22'],
            ['centre_name'=>'ZAMOKUNZEZELA', 'area_officer'=>'PHUMZILE', 'group_name'=>'AMKELANI', 'created_at'=>'2022-05-22'],
            ['centre_name'=>'SIZANANI', 'area_officer'=>'PHUMZILE', 'group_name'=>'IMBEWU', 'created_at'=>'2022-05-22'],
            ['centre_name'=>'SIZANANI', 'area_officer'=>'PHUMZILE', 'group_name'=>'SEED', 'created_at'=>'2022-05-22'],
            ['centre_name'=>'SIZANANI', 'area_officer'=>'PHUMZILE', 'group_name'=>'SIMUNYE', 'created_at'=>'2022-05-22'],
            ['centre_name'=>'SIZANANI', 'area_officer'=>'PHUMZILE', 'group_name'=>'SINAZO', 'created_at'=>'2022-05-22'],
            ['centre_name'=>'SIZANANI', 'area_officer'=>'PHUMZILE', 'group_name'=>'IMBOKONDO', 'created_at'=>'2022-05-22'],
            ['centre_name'=>'SIZANANI', 'area_officer'=>'PHUMZILE', 'group_name'=>'PHAPHAMANI', 'created_at'=>'2022-08-22'],
            ['centre_name'=>'OGADE', 'area_officer'=>'PHUMZILE', 'group_name'=>'SIZAKACANE', 'created_at'=>'2022-05-22'],
            ['centre_name'=>'OGADE', 'area_officer'=>'PHUMZILE', 'group_name'=>'SIZAKALA', 'created_at'=>'2022-05-22'],
            ['centre_name'=>'OGADE', 'area_officer'=>'PHUMZILE', 'group_name'=>'SIZANANI', 'created_at'=>'2022-05-22'],
            ['centre_name'=>'OGADE', 'area_officer'=>'PHUMZILE', 'group_name'=>'MASAKHANE', 'created_at'=>'2022-05-22'],
            ['centre_name'=>'OGADE', 'area_officer'=>'PHUMZILE', 'group_name'=>'VUKUZENZELE', 'created_at'=>'2022-05-22'],
            ['centre_name'=>'OGADE', 'area_officer'=>'PHUMZILE', 'group_name'=>'LETHUKUTHUKA', 'created_at'=>'2022-05-22'],
            ['centre_name'=>'OGADE', 'area_officer'=>'PHUMZILE', 'group_name'=>'NTABAKUNETHA', 'created_at'=>'2022-08-22'],
            ['centre_name'=>'HOFFELNTAIL', 'area_officer'=>'PHUMZILE', 'group_name'=>'KHULUZE', 'created_at'=>'2022-08-22'],
            ['centre_name'=>'HOFFELNTAIL', 'area_officer'=>'PHUMZILE', 'group_name'=>'NONKONGO', 'created_at'=>'2022-08-22'],
            ['centre_name'=>'HOFFELNTAIL', 'area_officer'=>'PHUMZILE', 'group_name'=>'THANDIMPILO', 'created_at'=>'2022-08-22'],
            ['centre_name'=>'INQUBEKO', 'area_officer'=>'BUHLE', 'group_name'=>'ZAMANI', 'created_at'=>'2022-05-22'],
            ['centre_name'=>'INQUBEKO', 'area_officer'=>'BUHLE', 'group_name'=>'MBALEHLE', 'created_at'=>'2022-05-22'],
            ['centre_name'=>'INQUBEKO', 'area_officer'=>'BUHLE', 'group_name'=>'ZANOKUHLE', 'created_at'=>'2022-05-22'],
            ['centre_name'=>'INQUBEKO', 'area_officer'=>'BUHLE', 'group_name'=>'ITHUBELIHLE', 'created_at'=>'2022-05-22'],
            ['centre_name'=>'INQUBEKO', 'area_officer'=>'BUHLE', 'group_name'=>'ITHEMBALOKUGCINA', 'created_at'=>'2022-05-22'],
            ['centre_name'=>'INQUBEKO', 'area_officer'=>'BUHLE', 'group_name'=>'QEDUSIZI', 'created_at'=>'2022-05-22'],
            ['centre_name'=>'HLANGANANI', 'area_officer'=>'BUHLE', 'group_name'=>'MASISIZANE', 'created_at'=>'2022-06-22'],
            ['centre_name'=>'HLANGANANI', 'area_officer'=>'BUHLE', 'group_name'=>'SIZAKANCANE', 'created_at'=>'2022-06-22'],
            ['centre_name'=>'HLANGANANI', 'area_officer'=>'BUHLE', 'group_name'=>'SIYAFUFUSA', 'created_at'=>'2022-06-22'],
            ['centre_name'=>'HLANGANANI', 'area_officer'=>'BUHLE', 'group_name'=>'BAMBANANI', 'created_at'=>'2022-08-22'],
            ['centre_name'=>'BUHLEBUYEZA', 'area_officer'=>'BUHLE', 'group_name'=>'MASIBUMBANE', 'created_at'=>'2022-06-22'],
            ['centre_name'=>'BUHLEBUYEZA', 'area_officer'=>'BUHLE', 'group_name'=>'VUKUZAME', 'created_at'=>'2022-06-22'],
            ['centre_name'=>'BUHLEBUYEZA', 'area_officer'=>'BUHLE', 'group_name'=>'SIYATHUTHUKA', 'created_at'=>'2022-06-22'],
            ['centre_name'=>'SIZANOKUHLE', 'area_officer'=>'BUHLE', 'group_name'=>'SIMUNYE', 'created_at'=>'2022-08-22'],
            ['centre_name'=>'SIZANOKUHLE', 'area_officer'=>'BUHLE', 'group_name'=>'VUKASIZWE', 'created_at'=>'2022-08-22'],
            ['centre_name'=>'ZAMOKUHLE', 'area_officer'=>'BUHLE', 'group_name'=>'ZANOTHANDO', 'created_at'=>'2022-05-22'],
            ['centre_name'=>'ZAMOKUHLE', 'area_officer'=>'BUHLE', 'group_name'=>'THUTHUKA', 'created_at'=>'2022-05-22'],
            ['centre_name'=>'ZAMOKUHLE', 'area_officer'=>'BUHLE', 'group_name'=>'ZAMANANI', 'created_at'=>'2022-05-22'],
            ['centre_name'=>'ZAMOKUHLE', 'area_officer'=>'BUHLE', 'group_name'=>'MASIBAMBANE', 'created_at'=>'2022-05-22'],
            ['centre_name'=>'ZAMOKUHLE', 'area_officer'=>'BUHLE', 'group_name'=>'SIYATHUTHUKA', 'created_at'=>'2022-05-22'],
            ['centre_name'=>'ZAMOKUHLE', 'area_officer'=>'BUHLE', 'group_name'=>'ZENZELE', 'created_at'=>'2022-05-22'],
            ['centre_name'=>'ZAMOKUHLE', 'area_officer'=>'BUHLE', 'group_name'=>'ICEBOLETHU', 'created_at'=>'2022-05-22'],
            ['centre_name'=>'MOGOLANENG', 'area_officer'=>'SARAH', 'group_name'=>'MAHLATSE', 'created_at'=>'2022-06-22'],
            ['centre_name'=>'MOGOLANENG', 'area_officer'=>'SARAH', 'group_name'=>'ITEKENG', 'created_at'=>'2022-06-22'],
            ['centre_name'=>'MOGOLANENG', 'area_officer'=>'SARAH', 'group_name'=>'RETLAKGONA', 'created_at'=>'2022-06-22'],
            ['centre_name'=>'MOGOLANENG', 'area_officer'=>'SARAH', 'group_name'=>'THUSANANG', 'created_at'=>'2022-06-22'],
            ['centre_name'=>'MOGOLANENG', 'area_officer'=>'SARAH', 'group_name'=>'RATANANG', 'created_at'=>'2022-06-22'],
            ['centre_name'=>'MOGOLANENG', 'area_officer'=>'SARAH', 'group_name'=>'LESEDI', 'created_at'=>'2022-06-22'],
            ['centre_name'=>'MOGOLANENG', 'area_officer'=>'SARAH', 'group_name'=>'MASECHABA', 'created_at'=>'2022-06-22'],
            ['centre_name'=>'MOGOLANENG', 'area_officer'=>'SARAH', 'group_name'=>'BAITSHEPI', 'created_at'=>'2022-06-22'],
            ['centre_name'=>'MOGOLANENG', 'area_officer'=>'SARAH', 'group_name'=>'KWANANG', 'created_at'=>'2022-06-22'],
            ['centre_name'=>'MOGOLANENG', 'area_officer'=>'SARAH', 'group_name'=>'KAMANO', 'created_at'=>'2022-07-22'],
            ['centre_name'=>'MOHLAHLANENG', 'area_officer'=>'SARAH', 'group_name'=>'STRONG TOWER', 'created_at'=>'2022-07-22'],
            ['centre_name'=>'MOHLAHLANENG', 'area_officer'=>'SARAH', 'group_name'=>'NEVER GIVE UP', 'created_at'=>'2022-07-22'],
            ['centre_name'=>'MOHLAHLANENG', 'area_officer'=>'SARAH', 'group_name'=>'MOSEBJADI', 'created_at'=>'2022-07-22'],
            ['centre_name'=>'MABULELA', 'area_officer'=>'SARAH', 'group_name'=>'TIRISHANO', 'created_at'=>'2022-06-22'],
            ['centre_name'=>'MABULELA', 'area_officer'=>'SARAH', 'group_name'=>'IPOPENG', 'created_at'=>'2022-06-22'],
            ['centre_name'=>'MABULELA', 'area_officer'=>'SARAH', 'group_name'=>'LETHABO', 'created_at'=>'2022-06-22'],
            ['centre_name'=>'MABULELA', 'area_officer'=>'SARAH', 'group_name'=>'LOTANANG', 'created_at'=>'2022-06-22'],
            ['centre_name'=>'MABULELA', 'area_officer'=>'SARAH', 'group_name'=>'TSHEPHANG', 'created_at'=>'2022-06-22'],
            ['centre_name'=>'MABULELA', 'area_officer'=>'SARAH', 'group_name'=>'TSHOMISANO', 'created_at'=>'2022-07-22'],
            ['centre_name'=>'MAKGOBA', 'area_officer'=>'SARAH', 'group_name'=>'KHUTSANG', 'created_at'=>'2022-06-22'],
            ['centre_name'=>'MAKGOBA', 'area_officer'=>'SARAH', 'group_name'=>'DIMAKATSO', 'created_at'=>'2022-06-22'],
            ['centre_name'=>'MAKGOBA', 'area_officer'=>'SARAH', 'group_name'=>'PHELADI', 'created_at'=>'2022-06-22'],
            ['centre_name'=>'MAKGOBA', 'area_officer'=>'SARAH', 'group_name'=>'TSAKANE', 'created_at'=>'2022-06-22'],
            ['centre_name'=>'MAKGOBA', 'area_officer'=>'SARAH', 'group_name'=>'RETHABILE', 'created_at'=>'2022-06-22'],
            ['centre_name'=>'MAKGOBA', 'area_officer'=>'SARAH', 'group_name'=>'BANARENG', 'created_at'=>'2022-07-22'],
            ['centre_name'=>'BOGALATLADI', 'area_officer'=>'SARAH', 'group_name'=>'IKAGENG', 'created_at'=>'2022-07-22'],
            ['centre_name'=>'MARULANENG', 'area_officer'=>'DIPUO', 'group_name'=>'TSUNAMI', 'created_at'=>'2022-05-22'],
            ['centre_name'=>'MARULANENG', 'area_officer'=>'DIPUO', 'group_name'=>'TOGETHER', 'created_at'=>'2022-05-22'],
            ['centre_name'=>'MARULANENG', 'area_officer'=>'DIPUO', 'group_name'=>'BATLOKWA', 'created_at'=>'2022-05-22'],
            ['centre_name'=>'MARULANENG', 'area_officer'=>'DIPUO', 'group_name'=>'GOPOLANG', 'created_at'=>'2022-05-22'],
            ['centre_name'=>'MARULANENG', 'area_officer'=>'DIPUO', 'group_name'=>'TIANGMAATLA', 'created_at'=>'2022-05-22'],
            ['centre_name'=>'MARULANENG', 'area_officer'=>'DIPUO', 'group_name'=>'IKEMELENG', 'created_at'=>'2022-05-22'],
            ['centre_name'=>'MARULANENG', 'area_officer'=>'DIPUO', 'group_name'=>'NALEDI', 'created_at'=>'2022-06-22'],
            ['centre_name'=>'MARULANENG', 'area_officer'=>'DIPUO', 'group_name'=>'LETHABO', 'created_at'=>'2022-07-22'],
            ['centre_name'=>'MARULANENG', 'area_officer'=>'DIPUO', 'group_name'=>'MASHEGOMASHEGO', 'created_at'=>'2022-07-22'],
            ['centre_name'=>'MARULANENG', 'area_officer'=>'DIPUO', 'group_name'=>'KOPANO', 'created_at'=>'2022-07-22'],
            ['centre_name'=>'MARULANENG', 'area_officer'=>'DIPUO', 'group_name'=>'AMOGELANG', 'created_at'=>'2022-07-22'],
            ['centre_name'=>'MARULANENG', 'area_officer'=>'DIPUO', 'group_name'=>'IPOPENG', 'created_at'=>'2022-07-22'],
            ['centre_name'=>'MORETSELA', 'area_officer'=>'DIPUO', 'group_name'=>'SWARANANG', 'created_at'=>'2022-05-22'],
            ['centre_name'=>'MORETSELA', 'area_officer'=>'DIPUO', 'group_name'=>'ITIRELENG', 'created_at'=>'2022-05-22'],
            ['centre_name'=>'MORETSELA', 'area_officer'=>'DIPUO', 'group_name'=>'KOPANO', 'created_at'=>'2022-05-22'],
            ['centre_name'=>'MORETSELA', 'area_officer'=>'DIPUO', 'group_name'=>'KGAOGELO', 'created_at'=>'2022-05-22'],
            ['centre_name'=>'MORETSELA', 'area_officer'=>'DIPUO', 'group_name'=>'BAIPEREKI', 'created_at'=>'2022-05-22'],
            ['centre_name'=>'MORETSELA', 'area_officer'=>'DIPUO', 'group_name'=>'THEKGANANG', 'created_at'=>'2022-05-22'],
            ['centre_name'=>'MORETSELA', 'area_officer'=>'DIPUO', 'group_name'=>'AGANANG', 'created_at'=>'2022-05-22'],
            ['centre_name'=>'MORETSELA', 'area_officer'=>'DIPUO', 'group_name'=>'TSEBANANG', 'created_at'=>'2022-05-22'],
            ['centre_name'=>'MORETSELA', 'area_officer'=>'DIPUO', 'group_name'=>'SIZANANG', 'created_at'=>'2022-05-22'],
            ['centre_name'=>'MORETSELA', 'area_officer'=>'DIPUO', 'group_name'=>'IKAGENG', 'created_at'=>'2022-07-22'],
            ['centre_name'=>'MORETSELA', 'area_officer'=>'DIPUO', 'group_name'=>'SHLOVO', 'created_at'=>'2022-07-22'],
            ['centre_name'=>'MORETSELA', 'area_officer'=>'DIPUO', 'group_name'=>'RATANANG', 'created_at'=>'2022-07-22'],
            ['centre_name'=>'MARIKANA', 'area_officer'=>'DIPUO', 'group_name'=>'SUNRISE', 'created_at'=>'2022-05-22'],
            ['centre_name'=>'MARIKANA', 'area_officer'=>'DIPUO', 'group_name'=>'ITSHEPENG', 'created_at'=>'2022-05-22'],
            ['centre_name'=>'MARIKANA', 'area_officer'=>'DIPUO', 'group_name'=>'KOPANO', 'created_at'=>'2022-05-22'],
            ['centre_name'=>'MARIKANA', 'area_officer'=>'DIPUO', 'group_name'=>'LERULENG', 'created_at'=>'2022-05-22'],
            ['centre_name'=>'MARIKANA', 'area_officer'=>'DIPUO', 'group_name'=>'HLOMPHANANG', 'created_at'=>'2022-05-22'],
            ['centre_name'=>'MARIKANA', 'area_officer'=>'DIPUO', 'group_name'=>'ATLEGANG', 'created_at'=>'2022-05-22'],
            ['centre_name'=>'MARIKANA', 'area_officer'=>'DIPUO', 'group_name'=>'FANANGDIATLA', 'created_at'=>'2022-05-22'],
            ['centre_name'=>'MARIKANA', 'area_officer'=>'DIPUO', 'group_name'=>'KATLEGO', 'created_at'=>'2022-05-22'],
            ['centre_name'=>'MARIKANA', 'area_officer'=>'DIPUO', 'group_name'=>'SEYAXHOBA', 'created_at'=>'2022-05-22'],
            ['centre_name'=>'MARIKANA', 'area_officer'=>'DIPUO', 'group_name'=>'BAITSHEPI', 'created_at'=>'2022-05-22'],
            ['centre_name'=>'MARIKANA', 'area_officer'=>'DIPUO', 'group_name'=>'RATANANG', 'created_at'=>'2022-07-22'],
            ['centre_name'=>'MARIKANA', 'area_officer'=>'DIPUO', 'group_name'=>'BAHUMI', 'created_at'=>'2022-06-22'],
            ['centre_name'=>'MARIKANA', 'area_officer'=>'DIPUO', 'group_name'=>'MEHLARENG', 'created_at'=>'2022-06-22'],
            ['centre_name'=>'MARIKANA', 'area_officer'=>'DIPUO', 'group_name'=>'LESEDI', 'created_at'=>'2022-05-22'],
            ['centre_name'=>'MARIKANA', 'area_officer'=>'DIPUO', 'group_name'=>'MOTHEO', 'created_at'=>'2022-07-22'],
            ['centre_name'=>'MARIKANA', 'area_officer'=>'DIPUO', 'group_name'=>'REPHOLOSHITSWE', 'created_at'=>'2022-07-22'],
            ['centre_name'=>'DICHOUENG', 'area_officer'=>'DIPUO', 'group_name'=>'THUSANANG', 'created_at'=>'2022-06-22'],
            ['centre_name'=>'DICHOUENG', 'area_officer'=>'DIPUO', 'group_name'=>'TSHEPANANG', 'created_at'=>'2022-06-22'],
            ['centre_name'=>'DICHOUENG', 'area_officer'=>'DIPUO', 'group_name'=>'IKAGENG', 'created_at'=>'2022-06-22'],
        ];

        foreach($groups as $group) {
            $centre = Centre::where('name',$group['centre_name'])->get()->first();

            DB::table('groups')->insert([       
                    'name'=>$group['group_name'],
                    // 'group_number'=>'G0',
                    // 'loan_term'=>'6 months',
                    // 'zone_name'=>'test zone',
                    // 'zone_code'=>'000',
                    // 'bank_account_name'=>'FNB',
                    // 'bank_account_number'=>'000',
                    // 'meeting_day',
                    // 'meeting_time',
                    'centre_id'=>$centre->id ?? $group['centre_name'],
                    'creator_id'=>1,
                    // 'area_code'=>'123',

                    'area_officer'=>$group['area_officer'],
                    'slug'=>strtolower(str_replace(' ', '-',$group['group_name'])),
                    'created_at' => Carbon::parse($group['created_at']),
                    'updated_at' => Carbon::now(),
                ]);
        }
    }
}
